WITH CRRT_ORDERS AS (
	SELECT DISTINCT
		ENCNTR_ALIAS.ALIAS AS FIN,
		ENCOUNTER.ENCNTR_ID,
		-- ENCOUNTER.PERSON_ID,
		ORDERS.ORDER_ID,
		pi_from_gmt(ORDERS.ORIG_ORDER_DT_TM, 'America/Chicago') AS ORDER_DATETIME,
		ORDERS.ORDER_MNEMONIC,
		pi_get_cv_display(ENCOUNTER.LOC_NURSE_UNIT_CD) AS NURSE_UNIT,
		MED_IDENTIFIER.VALUE AS PRODUCT
	FROM 
		ENCNTR_ALIAS,
		ENCNTR_DOMAIN,
		ENCOUNTER,
		ORDERS,
		MED_IDENTIFIER,
		ORDER_PRODUCT
	WHERE
		ENCNTR_DOMAIN.LOC_FACILITY_CD IN (
			3310, -- HH HERMANN
			3796, -- HC Childrens
			3821, -- HH Clinics
			3822, -- HH Trans Care
			3823 -- HH Rehab		
		)
		AND ENCNTR_DOMAIN.END_EFFECTIVE_DT_TM > DATE '2099-12-31'
		AND ENCNTR_DOMAIN.ENCNTR_ID = ENCOUNTER.ENCNTR_ID
		AND ENCOUNTER.DISCH_DT_TM IS NULL
		AND ENCNTR_DOMAIN.PERSON_ID = ORDERS.PERSON_ID
		AND ENCNTR_DOMAIN.ENCNTR_ID = ORDERS.ENCNTR_ID
		AND ORDERS.CATALOG_CD = 118901593 -- physiological irrigating solution
		AND ORDERS.PATHWAY_CATALOG_ID = 1005419855 -- CRRT NxStage Orders MPP
		AND ORDERS.DISCONTINUE_EFFECTIVE_DT_TM IS NULL
		AND ENCOUNTER.LOC_FACILITY_CD IN (
			3310, -- HH HERMANN
			3796, -- HC Childrens
			3821, -- HH Clinics
			3822, -- HH Trans Care
			3823 -- HH Rehab		
		)
		AND ORDERS.ORDER_ID = ORDER_PRODUCT.ORDER_ID
		-- AND ORDER_PRODUCT.ACTION_SEQUENCE = 1
		-- AND ORDER_PRODUCT.INGRED_SEQUENCE = 1
		AND ORDER_PRODUCT.ITEM_ID = MED_IDENTIFIER.ITEM_ID
		AND MED_IDENTIFIER.MED_IDENTIFIER_TYPE_CD = 1564 -- Generic Name
		AND MED_IDENTIFIER.MED_PRODUCT_ID = 0
		/* 	AND MED_IDENTIFIER.ITEM_ID IN (
			2892797, -- DOBUTamine 1000mg/250 ml D5W premix
			2896042, -- DOBUTamine 250 mg/20ml INJ VL
			153497896 -- DOBUTamine 4 mg/mL INJ (ANES)
		) */
		AND ENCOUNTER.ENCNTR_ID = ENCNTR_ALIAS.ENCNTR_ID
		AND ENCNTR_ALIAS.ENCNTR_ALIAS_TYPE_CD = 619 -- FIN NBR
		AND ENCNTR_ALIAS.ACTIVE_IND = 1
), CRRT_OUT AS (
	SELECT DISTINCT
		-- CRRT_ORDERS.ENCNTR_ID,
		CRRT_ORDERS.ORDER_ID,
		MAX(pi_from_gmt(CLINICAL_EVENT.EVENT_END_DT_TM, 'America/Chicago')) AS LAST_DATETIME
	FROM
		CLINICAL_EVENT,
		CRRT_ORDERS
	WHERE
		CRRT_ORDERS.ENCNTR_ID = CLINICAL_EVENT.ENCNTR_ID
		AND CLINICAL_EVENT.EVENT_CD IN (
			333892112, -- CRRT Output Vol
			173565025 -- CRRT Actual Pt Fluid Removed Vol
		)
		-- AND CLINICAL_EVENT.EVENT_END_DT_TM BETWEEN pi_to_gmt(SYSDATE - 1, 'America/Chicago') AND pi_to_gmt(SYSDATE, 'America/Chicago')
		AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
	GROUP BY
		CRRT_ORDERS.ORDER_ID
)

SELECT
	CRRT_ORDERS.*,
	CRRT_OUT.LAST_DATETIME
FROM
	CRRT_OUT,
	CRRT_ORDERS
WHERE
	CRRT_ORDERS.ORDER_ID = CRRT_OUT.ORDER_ID(+)