WITH DOSES AS (
	SELECT DISTINCT
		ENCOUNTER.ENCNTR_ID,
		ENCOUNTER.PERSON_ID,
		CLINICAL_EVENT.EVENT_ID,
		CLINICAL_EVENT.ORDER_ID,
		CASE 
			WHEN ORDERS.TEMPLATE_ORDER_ID = 0 THEN ORDERS.ORDER_ID
			ELSE ORDERS.TEMPLATE_ORDER_ID
		END AS ORIG_ORDER_ID,
		ENCOUNTER.ARRIVE_DT_TM,
		ORDERS.ORIG_ORDER_DT_TM,
		CLINICAL_EVENT.EVENT_END_DT_TM,
		pi_from_gmt(CLINICAL_EVENT.EVENT_END_DT_TM, 'America/Chicago') AS DOSE_DATETIME,
		CE_MED_RESULT.ADMIN_DOSAGE,
		CE_MED_RESULT.INFUSION_RATE,
		CE_MED_RESULT.INFUSION_UNIT_CD,
		pi_get_cv_display(CE_MED_RESULT.INFUSION_UNIT_CD) AS INFUSION_UNIT,
		CE_MED_RESULT.IV_EVENT_CD,
		pi_get_cv_display(CE_MED_RESULT.IV_EVENT_CD) AS IV_EVENT,
		CLINICAL_EVENT.EVENT_CD,
		pi_get_cv_display(CLINICAL_EVENT.EVENT_CD) AS MEDICATION
	FROM
		CE_MED_RESULT,
		CLINICAL_EVENT,
		ENCOUNTER,
		ORDERS
	WHERE
		CLINICAL_EVENT.EVENT_CD IN (
			37556889, -- esmolol
			37557367, -- ketamine
			37557675, -- niCARdipine
			37558323 -- vasopressin
		)
		AND CLINICAL_EVENT.EVENT_END_DT_TM BETWEEN
			pi_to_gmt(SYSDATE - 1, 'America/Chicago')
			AND pi_to_gmt(SYSDATE, 'America/Chicago')
		AND CLINICAL_EVENT.EVENT_ID = CE_MED_RESULT.EVENT_ID
		AND CE_MED_RESULT.IV_EVENT_CD > 0
		AND CLINICAL_EVENT.ENCNTR_ID = ENCOUNTER.ENCNTR_ID
		AND ENCOUNTER.LOC_FACILITY_CD IN (
			3310, -- HH HERMANN
			3796, -- HC Childrens
			3821, -- HH Clinics
			3822, -- HH Trans Care
			3823 -- HH Rehab		
		)
		AND CLINICAL_EVENT.ORDER_ID = ORDERS.ORDER_ID
		/* AND CLINICAL_EVENT.ORDER_ID = ORDER_PRODUCT.ORDER_ID
		AND ORDER_PRODUCT.ITEM_ID IN (
			275733495, -- ketAMINE 10 mg/mL in NS 50 mL syringe
			2931843, -- ketAMINE 500 mg/10 ml INJ VL
			304408345, -- ketAMINE 2000mg/NS 200ml (10mg/ml)
			3639548, -- esmolol 2500 mg-NS 250 ml premix
			234040263, -- esmolol 2500 mg/H20 250 mL Premix
			2894335, -- esmolol 100 mg/10 ml INJ VL
			89066190, -- niCARdipine 20mg/NS 200ml IV Soln
			89066350, -- niCARdipine 40 mg/ NS 200 ml IV Soln (premix)
			245273967 -- vasopressin 0.2 unit/mL (20 unit/100 mL) INJ
		)  */
), ACTIONS AS (
	SELECT
		DOSES.ENCNTR_ID,
		DOSES.EVENT_ID,
		DOSES.ORIG_ORDER_ID,
		MAX(ORDER_ACTION.ACTION_SEQUENCE) AS ACTION_SEQUENCE
	FROM
		DOSES,
		ORDER_ACTION
	WHERE
		DOSES.ORIG_ORDER_ID = ORDER_ACTION.ORDER_ID
		AND ORDER_ACTION.ACTION_DT_TM < DOSES.EVENT_END_DT_TM
	GROUP BY
		DOSES.ENCNTR_ID,
		DOSES.EVENT_ID,
		DOSES.ORIG_ORDER_ID
), MED_PRODS AS (
	SELECT
		ACTIONS.ENCNTR_ID,
		ACTIONS.EVENT_ID,
		ACTIONS.ORIG_ORDER_ID,
		ACTIONS.ACTION_SEQUENCE,
		ORDER_PRODUCT.ITEM_ID,
		ORDER_PRODUCT.DOSE_QUANTITY,
		ORDER_PRODUCT.DOSE_QUANTITY_UNIT_CD,
		pi_get_cv_display(ORDER_PRODUCT.DOSE_QUANTITY_UNIT_CD) AS DOSE_QUANTITY_UNIT
	FROM
		ACTIONS,
		ORDER_PRODUCT
	WHERE
		ACTIONS.ORIG_ORDER_ID = ORDER_PRODUCT.ORDER_ID
		AND ACTIONS.ACTION_SEQUENCE = ORDER_PRODUCT.ACTION_SEQUENCE
		AND ORDER_PRODUCT.INGRED_SEQUENCE = 1
), DOSES_PRODS AS (
	SELECT
		DOSES.*,
		MED_PRODS.ITEM_ID,
		MED_IDENTIFIER.VALUE AS MED_PRODUCT,
		MED_PRODS.DOSE_QUANTITY,
		MED_PRODS.DOSE_QUANTITY_UNIT
	FROM
		DOSES,
		MED_IDENTIFIER,
		MED_PRODS
	WHERE
		DOSES.EVENT_ID = MED_PRODS.EVENT_ID(+)
		AND MED_PRODS.ITEM_ID = MED_IDENTIFIER.ITEM_ID(+)
		AND MED_IDENTIFIER.MED_IDENTIFIER_TYPE_CD(+) = 1564 -- Description
		AND MED_IDENTIFIER.MED_PRODUCT_ID(+) = 0
), LAST_CHARTED AS (
	SELECT DISTINCT
		DOSES_PRODS.ENCNTR_ID,
		DOSES_PRODS.ITEM_ID,
		MAX(DOSES_PRODS.EVENT_END_DT_TM) AS LAST_CHARTED_DT_TM
	FROM
		DOSES_PRODS
	WHERE
		DOSES_PRODS.ADMIN_DOSAGE > 0
		OR DOSES_PRODS.IV_EVENT_CD IN (
			688706, -- Begin Bag
			688709 -- Rate Change
		)
	GROUP BY 
		DOSES_PRODS.ENCNTR_ID,
		DOSES_PRODS.ITEM_ID
), BAGS_YESTERDAY AS (
	SELECT DISTINCT
		DOSES_PRODS.ENCNTR_ID,
		DOSES_PRODS.EVENT_CD,
		COUNT(DOSES_PRODS.EVENT_ID) AS BAGS_LAST_24H
	FROM
		DOSES_PRODS
	WHERE
		DOSES_PRODS.IV_EVENT_CD = 688706 -- Begin Bag
	GROUP BY 
		DOSES_PRODS.ENCNTR_ID,
		DOSES_PRODS.EVENT_CD
), WEIGHTS AS (
	SELECT DISTINCT
		DOSES_PRODS.ENCNTR_ID,
		MAX(CLINICAL_EVENT.RESUlT_VAL) KEEP (DENSE_RANK LAST ORDER BY DOSES_PRODS.EVENT_END_DT_TM, DOSES_PRODS.EVENT_ID) OVER (PARTITION BY DOSES_PRODS.ENCNTR_ID) AS PT_WEIGHT	
	FROM
		CLINICAL_EVENT,
		DOSES_PRODS
	WHERE
		DOSES_PRODS.ENCNTR_ID = CLINICAL_EVENT.ENCNTR_ID
		AND CLINICAL_EVENT.EVENT_CLASS_CD = 159 -- NUM
		AND DOSES_PRODS.PERSON_ID = CLINICAL_EVENT.PERSON_ID
		AND CLINICAL_EVENT.EVENT_CD = 30107 -- Weight
		AND CLINICAL_EVENT.EVENT_END_DT_TM <= DOSES_PRODS.EVENT_END_DT_TM
		AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31'	
		AND CLINICAL_EVENT.RESULT_UNITS_CD = 170 -- kg
), FINAL_DATA AS (
	SELECT DISTINCT
		pi_get_cv_display(DOSES_PRODS.EVENT_CD) AS MEDICATION,
		MAX(DOSES_PRODS.MED_PRODUCT) KEEP (DENSE_RANK LAST ORDER BY DOSES_PRODS.EVENT_END_DT_TM) AS MED_PRODUCT, 
		pi_get_cv_display(ENCOUNTER.LOC_NURSE_UNIT_CD) AS CURRENT_NURSE_UNIT,
		ENCNTR_ALIAS.ALIAS AS FIN,
		PERSON.NAME_FULL_FORMATTED AS NAME,
		pi_from_gmt(LAST_CHARTED.LAST_CHARTED_DT_TM, 'America/Chicago') AS LAST_CHARTED_DATETIME,
		MAX(DOSES_PRODS.INFUSION_RATE) KEEP (DENSE_RANK LAST ORDER BY DOSES_PRODS.EVENT_END_DT_TM) AS RATE, 
		pi_get_cv_display(MAX(DOSES_PRODS.INFUSION_UNIT_CD) KEEP (DENSE_RANK LAST ORDER BY DOSES_PRODS.EVENT_END_DT_TM)) AS RATE_UNITS,
		MED_DISPENSE.STRENGTH,
		pi_get_cv_display(MED_DISPENSE.STRENGTH_UNIT_CD) AS STRENGTH_UNITS,
		MED_DISPENSE.VOLUME,
		pi_get_cv_display(MED_DISPENSE.VOLUME_UNIT_CD) AS VOLUME_UNITS,
		BAGS_YESTERDAY.BAGS_LAST_24H,
		DOSES_PRODS.DOSE_QUANTITY,
		DOSES_PRODS.DOSE_QUANTITY_UNIT,
		TO_NUMBER(COALESCE(ORDER_DETAIL.OE_FIELD_DISPLAY_VALUE, WEIGHTS.PT_WEIGHT)) AS WEIGHT_KG,
		MED_DISPENSE.STRENGTH * DOSES_PRODS.DOSE_QUANTITY AS STRENGTH_ADJ
	FROM
		BAGS_YESTERDAY,
		DOSES_PRODS,
		ENCNTR_ALIAS,
		ENCOUNTER,
		LAST_CHARTED,
		MED_DISPENSE,
		ORDER_DETAIL,
		ORDERS,
		PERSON,
		WEIGHTS
	WHERE
		DOSES_PRODS.ENCNTR_ID = LAST_CHARTED.ENCNTR_ID
		AND DOSES_PRODS.ITEM_ID = LAST_CHARTED.ITEM_ID
		AND DOSES_PRODS.ENCNTR_ID = BAGS_YESTERDAY.ENCNTR_ID
		AND DOSES_PRODS.EVENT_CD = BAGS_YESTERDAY.EVENT_CD
		AND DOSES_PRODS.ITEM_ID = MED_DISPENSE.ITEM_ID
		AND DOSES_PRODS.ENCNTR_ID = ENCOUNTER.ENCNTR_ID
		AND DOSES_PRODS.ENCNTR_ID = ENCNTR_ALIAS.ENCNTR_ID
		AND ENCNTR_ALIAS.ENCNTR_ALIAS_TYPE_CD = 619 -- FIN NBR
		AND DOSES_PRODS.PERSON_ID = PERSON.PERSON_ID
		AND DOSES_PRODS.IV_EVENT_CD IN (
			688706, -- Begin Bag
			688709 -- Rate Change
		)
		AND DOSES_PRODS.ORIG_ORDER_ID = ORDERS.ORDER_ID
		AND ORDERS.ORDER_STATUS_CD = 1386 -- Ordered
		AND ORDERS.ORDER_ID = ORDER_DETAIL.ORDER_ID(+)
		AND ORDER_DETAIL.OE_FIELD_MEANING_ID(+) = 99 -- WEIGHT
		AND ORDER_DETAIL.ACTION_SEQUENCE(+) = 1
		AND DOSES_PRODS.ENCNTR_ID = WEIGHTS.ENCNTR_ID
		AND DOSES_PRODS.ITEM_ID IN (
			275733495, -- ketAMINE 10 mg/mL in NS 50 mL syringe
			2931843, -- ketAMINE 500 mg/10 ml INJ VL
			2909223, -- ketAMINE 500 mg/5 ml INJ VL
			304408345, -- ketAMINE 2000mg/NS 200ml (10mg/ml)
			3639548, -- esmolol 2500 mg-NS 250 ml premix
			234040263, -- esmolol 2500 mg/H20 250 mL Premix
			2894335, -- esmolol 100 mg/10 ml INJ VL
			89066190, -- niCARdipine 20mg/NS 200ml IV Soln
			89066350, -- niCARdipine 40 mg/ NS 200 ml IV Soln (premix)
			245273967 -- vasopressin 0.2 unit/mL (20 unit/100 mL) INJ		
		)
	GROUP BY
		DOSES_PRODS.EVENT_CD,
		DOSES_PRODS.ORIG_ORDER_ID,
		ENCOUNTER.LOC_NURSE_UNIT_CD,
		ENCNTR_ALIAS.ALIAS,
		PERSON.NAME_FULL_FORMATTED,
		LAST_CHARTED.LAST_CHARTED_DT_TM,
		ORDERS.ORDER_STATUS_CD,
		ORDER_DETAIL.OE_FIELD_DISPLAY_VALUE,
		MED_DISPENSE.STRENGTH,
		MED_DISPENSE.STRENGTH_UNIT_CD,
		MED_DISPENSE.VOLUME,
		MED_DISPENSE.VOLUME_UNIT_CD,
		BAGS_YESTERDAY.BAGS_LAST_24H,
		DOSES_PRODS.DOSE_QUANTITY,
		DOSES_PRODS.DOSE_QUANTITY_UNIT,
		WEIGHTS.PT_WEIGHT
), FINAL_RATE AS (
	SELECT
		FINAL_DATA.*,
		CASE
			WHEN RATE_UNITS = 'microgram/kg/min' THEN RATE / 1000 * 60 * WEIGHT_KG
			WHEN RATE_UNITS = 'mg/kg/hr' THEN RATE * WEIGHT_KG
			WHEN RATE_UNITS = 'unit/min' THEN RATE * 60
			ELSE RATE
		END AS RATE_MG_HR
	FROM
		FINAL_DATA
)

SELECT 
	FINAL_RATE.*,
	CEIL(RATE_MG_HR / STRENGTH_ADJ * 24) AS BAGS_NEEDED_TODAY
FROM
	FINAL_RATE

-- //clinisilonhh/PHI_Access$/PHI-HER - Pharmacy Adult/Batch IV Current Rates