WITH OPIOIDS AS (
	SELECT DISTINCT
		CV_CLIN_EV.CODE_VALUE,
		CV_CLIN_EV.DISPLAY
	FROM
		CODE_VALUE,
		CODE_VALUE CV_CLIN_EV,
		PI_THERA_CLASS_VIEW
	WHERE
		PI_THERA_CLASS_VIEW.DRUG_CAT IN (
			'narcotic analgesic combinations', 
			'narcotic analgesics'
		)
		AND PI_THERA_CLASS_VIEW.DRUG_CAT_CD = CODE_VALUE.CODE_VALUE
		AND CODE_VALUE.DISPLAY_KEY = CV_CLIN_EV.DISPLAY_KEY
		AND CV_CLIN_EV.CODE_SET = 72
)

SELECT DISTINCT
	ENCNTR_ALIAS.ALIAS AS FIN,
	CLINICAL_EVENT.EVENT_ID AS EVENT_ID,
	TO_CHAR(pi_from_gmt(CLINICAL_EVENT.EVENT_END_DT_TM, (pi_time_zone(1, @Variable('BOUSER')))), 'YYYY-MM-DD"T"HH24:MI:SS') AS EVENT_DATETIME,
	pi_get_cv_display(CLINICAL_EVENT.EVENT_CD) AS MEDICATION,
	ORDERS.ORDER_MNEMONIC AS MED_PRODUCT,
	CE_MED_RESULT.ADMIN_DOSAGE AS DOSE,
	pi_get_cv_display(CE_MED_RESULT.DOSAGE_UNIT_CD) AS DOSE_UNIT,
	CE_MED_RESULT.INFUSION_RATE AS RATE,
	pi_get_cv_display(CE_MED_RESULT.INFUSION_UNIT_CD) AS RATE_UNIT,
	pi_get_cv_display(CE_MED_RESULT.IV_EVENT_CD) AS IV_EVENT,
	pi_get_cv_display(CE_MED_RESULT.ADMIN_ROUTE_CD) AS ROUTE,
	pi_get_cv_display(ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD) AS NURSE_UNIT
FROM
	CE_MED_RESULT,
    CLINICAL_EVENT,
	ENCNTR_ALIAS,
	ENCNTR_LOC_HIST,
	ENCOUNTER,
	OPIOIDS,
	ORDERS
WHERE
    ENCNTR_ALIAS.ALIAS IN @prompt('Enter value(s) for Alias','A',,Multi,Free,Persistent,,User:0)
	AND ENCNTR_ALIAS.ENCNTR_ALIAS_TYPE_CD = 619
	AND ENCNTR_ALIAS.ENCNTR_ID = ENCOUNTER.ENCNTR_ID
	AND (
		OPIOIDS.CODE_VALUE = CLINICAL_EVENT.EVENT_CD
		AND ENCOUNTER.PERSON_ID = CLINICAL_EVENT.PERSON_ID
		AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31' 
		AND ENCOUNTER.ENCNTR_ID = CLINICAL_EVENT.ENCNTR_ID
		AND CLINICAL_EVENT.EVENT_CLASS_CD = 158 -- MED
	)
	AND (
		CLINICAL_EVENT.ENCNTR_ID = ENCNTR_LOC_HIST.ENCNTR_ID
		AND ENCNTR_LOC_HIST.BEG_EFFECTIVE_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
		AND ENCNTR_LOC_HIST.TRANSACTION_DT_TM = (
			SELECT MAX(ELH.TRANSACTION_DT_TM)
			FROM ENCNTR_LOC_HIST ELH
			WHERE
				CLINICAL_EVENT.ENCNTR_ID = ELH.ENCNTR_ID
				AND ELH.TRANSACTION_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
		)
		AND ENCNTR_LOC_HIST.END_EFFECTIVE_DT_TM >= CLINICAL_EVENT.EVENT_END_DT_TM
	)
	AND CLINICAL_EVENT.EVENT_ID = CE_MED_RESULT.EVENT_ID
	AND CLINICAL_EVENT.ORDER_ID = ORDERS.ORDER_ID
