WITH DOSES AS (
	SELECT DISTINCT
		CLINICAL_EVENT.ENCNTR_ID,
		CLINICAL_EVENT.EVENT_END_DT_TM,
		CLINICAL_EVENT.EVENT_ID,
		pi_get_cv_display(CLINICAL_EVENT.EVENT_CD) AS MEDICATION,
		pi_get_cv_display(ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD) AS NURSE_UNIT
	FROM
		CE_MED_RESULT,
		CLINICAL_EVENT,
		ENCNTR_LOC_HIST
		-- ENCOUNTER
		-- PERSON
	WHERE
		CLINICAL_EVENT.EVENT_CD IN (
			37557136, -- haloperidol
			37557716, -- olanzapine
			37557952, -- quetiapine
			37558381 -- ziprasidone
		) 
		AND CLINICAL_EVENT.EVENT_END_DT_TM BETWEEN
			pi_to_gmt(
				TO_DATE(
					@Prompt('Enter begin date', 'D', , mono, free, persistent, {'07/01/2019 00:00:00'}, User:0), 
					pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
				), 
				'America/Chicago'
			)
			AND pi_to_gmt(
				TO_DATE(
					@Prompt('Enter end date', 'D', , mono, free, persistent, {'7/01/2020 00:00:00'}, User:1), 
					pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
				) - 1/86400, 
				'America/Chicago'
			)
		AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
		AND CLINICAL_EVENT.EVENT_ID = CE_MED_RESULT.EVENT_ID
		AND CE_MED_RESULT.ADMIN_DOSAGE > 0
		AND CE_MED_RESULT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
		-- AND CLINICAL_EVENT.ENCNTR_ID = ENCOUNTER.ENCNTR_ID
		-- AND CLINICAL_EVENT.PERSON_ID = PERSON.PERSON_ID
		-- AND TRUNC(((pi_from_gmt(ENCOUNTER.REG_DT_TM, 'America/Chicago')) - PERSON.BIRTH_DT_TM) / 365.25, 0) >= 65
		AND CLINICAL_EVENT.ENCNTR_ID = ENCNTR_LOC_HIST.ENCNTR_ID
		AND ENCNTR_LOC_HIST.BEG_EFFECTIVE_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
		AND ENCNTR_LOC_HIST.TRANSACTION_DT_TM = (
			SELECT MAX(ELH.TRANSACTION_DT_TM)
			FROM ENCNTR_LOC_HIST ELH
			WHERE
				CLINICAL_EVENT.ENCNTR_ID = ELH.ENCNTR_ID
				AND ELH.TRANSACTION_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
		)
		AND ENCNTR_LOC_HIST.END_EFFECTIVE_DT_TM >= CLINICAL_EVENT.EVENT_END_DT_TM
		AND ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD IN (
			4356, -- HH 6EJP
			1542800, -- HH 6WJP
			16163788, -- HH 8NJP
			8667295, -- HH 3JP
			2428498395, -- HH S1MU
			3224987147, -- HH S SITU
			3224987399, -- HH S SIMU
			3224988029, -- HH S OTAC
			1846341943, -- HH 3CP
			1846342787, -- HH 3CIM
			3955, -- HH 4WCP
			265179687 -- HH ACE
		)
), NUM_DOSES AS (
	SELECT
		ENCNTR_ID,
		MEDICATION,
		NURSE_UNIT,
		COUNT(DISTINCT EVENT_ID) AS NUM_DOSES
	FROM DOSES
	GROUP BY
		ENCNTR_ID,
		MEDICATION,
		NURSE_UNIT
)

SELECT
	NUM_DOSES.*,
	ENCNTR_ALIAS.ALIAS AS FIN
FROM
	ENCNTR_ALIAS,
	NUM_DOSES
WHERE
	NUM_DOSES.ENCNTR_ID = ENCNTR_ALIAS.ENCNTR_ID
	AND ENCNTR_ALIAS.ENCNTR_ALIAS_TYPE_CD = 619 -- FIN NBR
	AND ENCNTR_ALIAS.ACTIVE_IND = 1

