SELECT DISTINCT
	CLINICAL_EVENT.ENCNTR_ID,
	CLINICAL_EVENT.EVENT_ID,
	pi_from_gmt(ORDERS.ORIG_ORDER_DT_TM, (pi_time_zone(1, @Variable('BOUSER')))) AS ORDER_DATETIME,
	pi_from_gmt(CLINICAL_EVENT.EVENT_END_DT_TM, (pi_time_zone(1, @Variable('BOUSER')))) AS DOSE_DATETIME,
	TRUNC(pi_from_gmt(CLINICAL_EVENT.EVENT_END_DT_TM, (pi_time_zone(1, @Variable('BOUSER')))), 'MONTH') AS DOSE_MONTH,
	pi_get_cv_display(ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD) AS NURSE_UNIT,
	ORDERS.ORDER_MNEMONIC AS MED_PRODUCT,
	ORDER_DETAIL.OE_FIELD_DISPLAY_VALUE AS DRUG_FORM
FROM 
	CE_MED_RESULT,
	CLINICAL_EVENT,
	ENCNTR_LOC_HIST,
	ORDER_DETAIL,
	ORDERS
WHERE
	CLINICAL_EVENT.EVENT_CD = 37556731 -- diazepam
	AND CLINICAL_EVENT.EVENT_END_DT_TM BETWEEN
		pi_to_gmt(DATE '2019-07-01', pi_time_zone(2, @Variable('BOUSER')))
		AND pi_to_gmt(DATE '2019-12-01', pi_time_zone(2, @Variable('BOUSER')))
	AND CLINICAL_EVENT.EVENT_ID = CE_MED_RESULT.EVENT_ID
	AND CE_MED_RESULT.ADMIN_DOSAGE > 0 
	AND CLINICAL_EVENT.ENCNTR_ID = ENCNTR_LOC_HIST.ENCNTR_ID
	AND ENCNTR_LOC_HIST.BEG_EFFECTIVE_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
	AND ENCNTR_LOC_HIST.TRANSACTION_DT_TM = (
		SELECT MAX(ELH.TRANSACTION_DT_TM)
		FROM ENCNTR_LOC_HIST ELH
		WHERE
			CLINICAL_EVENT.ENCNTR_ID = ELH.ENCNTR_ID
			AND ELH.TRANSACTION_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
	)
	AND ENCNTR_LOC_HIST.END_EFFECTIVE_DT_TM >= CLINICAL_EVENT.EVENT_END_DT_TM 
	AND ENCNTR_LOC_HIST.LOC_FACILITY_CD IN (
			3310, -- HH HERMANN
			3796, -- HC Childrens
			3821, -- HH Clinics
			3822, -- HH Trans Care
			3823, -- HH Rehab
			1099966301 -- HH Oncology TMC	
	)
	AND CLINICAL_EVENT.ORDER_ID = ORDERS.ORDER_ID
	AND ORDERS.ORDER_ID = ORDER_DETAIL.ORDER_ID
	AND ORDER_DETAIL.OE_FIELD_MEANING_ID = 2014 -- DRUGFORM
	AND ORDER_DETAIL.OE_FIELD_DISPLAY_VALUE = 'SOLN'
