WITH PATIENTS AS (
	SELECT DISTINCT
		ENCOUNTER.ENCNTR_ID,
		ENCOUNTER.PERSON_ID
	FROM
		ENCNTR_LOC_HIST,
		ENCOUNTER
	WHERE
		ENCOUNTER.ORGANIZATION_ID = 1 -- Memorial Hermann Hospital
		AND ENCOUNTER.ENCNTR_ID = ENCNTR_LOC_HIST.ENCNTR_ID
		AND ENCNTR_LOC_HIST.END_EFFECTIVE_DT_TM >= 
			DECODE(
				@Prompt('Choose date range', 'A', {'Yesterday', 'User-defined'}, mono, free, , , User:0),
				'Yesterday', pi_to_gmt(TRUNC(SYSDATE) - 1, 'America/Chicago'),
				'User-defined', pi_to_gmt(
					TO_DATE(
						@Prompt('Enter begin date', 'D', , mono, free, persistent, {'12/01/2022 00:00:00'}, User:1),
						pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
					),
					pi_time_zone(1, 'America/Chicago')
				)
			)
		AND ENCNTR_LOC_HIST.BEG_EFFECTIVE_DT_TM <= 
			DECODE(
				@Prompt('Choose date range', 'A', {'Yesterday', 'User-defined'}, mono, free, , , User:0),
				'Yesterday', pi_to_gmt(TRUNC(SYSDATE) - 1/86400, 'America/Chicago'),
				'User-defined', pi_to_gmt(
					TO_DATE(
						@Prompt('Enter end date', 'D', , mono, free, persistent, {'03/01/2023 00:00:00'}, User:2),
						pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
					) - 1/86400,
					pi_time_zone(1, 'America/Chicago')
				)
			)
		AND ENCNTR_LOC_HIST.LOC_FACILITY_CD IN (
			3310, -- HH HERMANN
			3796, -- HC Childrens
			3821, -- HH Clinics
			3822, -- HH Trans Care
			3823, -- HH Rehab
			1099966301 -- HH Oncology TMC	
		)		
		AND ENCNTR_LOC_HIST.ACTIVE_IND = 1
), PHARM_ORDERS AS (
	SELECT DISTINCT
		ORDERS.ENCNTR_ID,
		ORDERS.ORDER_ID,
		-- ORDERS.ORIG_ORDER_DT_TM,
		pi_get_cv_display(ENCNTR_LOC_HIST.LOC_FACILITY_CD) AS FACILITY,
		pi_get_cv_display(ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD) AS NURSE_UNIT,
		-- ORDER_DETAIL.OE_FIELD_DISPLAY_VALUE AS DISPENSE_FROM,
		DISPENSE_HX.DISPENSE_HX_ID,
		-- pi_from_gmt(DISPENSE_HX.DISPENSE_DT_TM, 'America/Chicago') AS DISPENSE_DATETIME,
		-- TRUNC(pi_from_gmt(DISPENSE_HX.DISPENSE_DT_TM, 'America/Chicago'), 'MONTH') AS DISPENSE_MONTH,
		pi_get_cv_display(DISPENSE_HX.DISP_EVENT_TYPE_CD) AS DISP_EVENT_TYPE,
		pi_get_cv_display(DISPENSE_HX.DISP_SR_CD) AS DISP_FROM
	FROM
		DISPENSE_HX,
		ENCNTR_LOC_HIST,
		-- ORDER_DETAIL,
		ORDERS,
		PATIENTS
	WHERE
		PATIENTS.ENCNTR_ID = ORDERS.ENCNTR_ID
		AND PATIENTS.PERSON_ID = ORDERS.PERSON_ID
		AND ORDERS.ACTIVITY_TYPE_CD = 378 -- Pharmacy
		AND ORDERS.CATALOG_TYPE_CD = 1363 -- Pharmacy
		-- AND ORDERS.ORDER_ID = ORDER_DETAIL.ORDER_ID(+)
		-- AND ORDER_DETAIL.ACTION_SEQUENCE = 1
		-- AND ORDER_DETAIL.OE_FIELD_MEANING_ID(+) = 2006 -- DISPENSEFROMLOC
		AND ORDERS.ORDER_ID = DISPENSE_HX.ORDER_ID(+)
		AND ORDERS.ENCNTR_ID = ENCNTR_LOC_HIST.ENCNTR_ID
		AND ENCNTR_LOC_HIST.BEG_EFFECTIVE_DT_TM <= ORDERS.ORIG_ORDER_DT_TM
		AND ENCNTR_LOC_HIST.TRANSACTION_DT_TM = (
			SELECT MAX(ELH.TRANSACTION_DT_TM)
			FROM ENCNTR_LOC_HIST ELH
			WHERE
				ORDERS.ENCNTR_ID = ELH.ENCNTR_ID
				AND ELH.TRANSACTION_DT_TM <= ORDERS.ORIG_ORDER_DT_TM
		)
		AND ENCNTR_LOC_HIST.LOC_FACILITY_CD IN (
			3310, -- HH HERMANN
			3796, -- HC Childrens
			3821, -- HH Clinics
			3822, -- HH Trans Care
			3823, -- HH Rehab
			1099966301 -- HH Oncology TMC	
		)
		AND ENCNTR_LOC_HIST.END_EFFECTIVE_DT_TM >= ORDERS.ORIG_ORDER_DT_TM
), CHILD_ORDERS AS (
	SELECT DISTINCT
		PHARM_ORDERS.*,
		ORDERS.ORDER_ID AS CHILD_ORDER_ID
	FROM
		PHARM_ORDERS,
		ORDERS
	WHERE
		PHARM_ORDERS.ORDER_ID = ORDERS.TEMPLATE_ORDER_ID(+)
), DOSES AS (
	SELECT DISTINCT
		CHILD_ORDERS.*,
		CLINICAL_EVENT.EVENT_ID
	FROM
		CE_MED_RESULT,
		CHILD_ORDERS,
		CLINICAL_EVENT
	WHERE
		COALESCE(CHILD_ORDERS.CHILD_ORDER_ID, CHILD_ORDERS.ORDER_ID) = CLINICAL_EVENT.ORDER_ID
		AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
		AND CLINICAL_EVENT.EVENT_ID = CE_MED_RESULT.EVENT_ID
		AND CE_MED_RESULT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
		AND (CE_MED_RESULT.ADMIN_DOSAGE > 0 OR CE_MED_RESULT.INFUSION_RATE > 0)	
)

SELECT
	FACILITY,
	DISP_EVENT_TYPE,
	-- DISP_FROM,
	COUNT(DISTINCT DISPENSE_HX_ID) AS NUM_DISPENSED,
	COUNT(DISTINCT EVENT_ID) AS NUM_ADMINISTERED
FROM
	DOSES
WHERE
	DOSES.DISP_EVENT_TYPE NOT IN ('Device Return', 'Manual Credit')
	AND REGEXP_INSTR(DOSES.NURSE_UNIT, '^CY') = 0
GROUP BY
	FACILITY,
	DISP_EVENT_TYPE
	-- DISP_FROM