WITH DOSES AS (
	SELECT DISTINCT
		ENCOUNTER.ENCNTR_ID,
		ENCOUNTER.PERSON_ID,
		CLINICAL_EVENT.EVENT_ID,
		CLINICAL_EVENT.ORDER_ID,
		ENCOUNTER.ARRIVE_DT_TM,
		CLINICAL_EVENT.EVENT_END_DT_TM,
		CE_MED_RESULT.INFUSION_RATE,
		CE_MED_RESULT.INFUSION_UNIT_CD,
		CE_MED_RESULT.IV_EVENT_CD,
		ORDER_PRODUCT.ITEM_ID
	FROM
		CE_MED_RESULT,
		CLINICAL_EVENT,
		--ENCNTR_LOC_HIST,
		ENCOUNTER,
		ORDER_PRODUCT
	WHERE
		CLINICAL_EVENT.EVENT_CD IN (
			37556889, -- esmolol
			37557367 -- ketamine
		)
		AND CLINICAL_EVENT.EVENT_END_DT_TM BETWEEN
			pi_to_gmt(SYSDATE - 1, pi_time_zone(2, @Variable('BOUSER')))
			AND pi_to_gmt(SYSDATE, pi_time_zone(2, @Variable('BOUSER')))
		AND CLINICAL_EVENT.EVENT_ID = CE_MED_RESULT.EVENT_ID
		AND CE_MED_RESULT.IV_EVENT_CD > 0
		AND CLINICAL_EVENT.ENCNTR_ID = ENCOUNTER.ENCNTR_ID
		AND ENCOUNTER.LOC_FACILITY_CD = 3310 -- HH HERMANN
		AND CLINICAL_EVENT.ORDER_ID = ORDER_PRODUCT.ORDER_ID
		AND ORDER_PRODUCT.ITEM_ID IN (
			275733495, -- ketAMINE 10 mg/mL in NS 50 mL syringe
			3639548 -- esmolol 2500 mg-NS 250 ml premix
		) 
)

SELECT DISTINCT
	MED_IDENTIFIER.VALUE AS MED_PRODUCT,
	pi_get_cv_display(ENCOUNTER.LOC_NURSE_UNIT_CD) AS CURRENT_NURSE_UNIT,
	ENCNTR_ALIAS.ALIAS AS FIN,
	PERSON.NAME_FULL_FORMATTED AS NAME,
	pi_from_gmt(MAX(DOSES.EVENT_END_DT_TM), (pi_time_zone(1, @Variable('BOUSER')))) AS LAST_RATE_DATETIME,
	MAX(DOSES.INFUSION_RATE) KEEP (DENSE_RANK LAST ORDER BY DOSES.EVENT_END_DT_TM) AS RATE, 
	pi_get_cv_display(MAX(DOSES.INFUSION_UNIT_CD) KEEP (DENSE_RANK LAST ORDER BY DOSES.EVENT_END_DT_TM)) AS RATE_UNITS,
	ORDER_DETAIL.OE_FIELD_DISPLAY_VALUE AS WEIGHT,
	OD_WT_UNITS.OE_FIELD_DISPLAY_VALUE AS WEIGHT_UNITS
FROM
	DOSES,
	ENCNTR_ALIAS,
	ENCOUNTER,
	MED_IDENTIFIER,
	ORDER_DETAIL,
	ORDER_DETAIL OD_WT_UNITS,
	ORDERS,
	PERSON
WHERE
	DOSES.ITEM_ID = MED_IDENTIFIER.ITEM_ID
	AND MED_IDENTIFIER.MED_IDENTIFIER_TYPE_CD = 1564 -- Description
	AND MED_IDENTIFIER.MED_PRODUCT_ID = 0
	AND DOSES.IV_EVENT_CD IN (
		688706, -- Begin Bag
		688709 -- Rate Change
	)
	AND DOSES.ORDER_ID = ORDERS.ORDER_ID
	AND ORDERS.ORDER_STATUS_CD = 1386 -- Ordered
	AND DOSES.ENCNTR_ID = ENCOUNTER.ENCNTR_ID
	AND DOSES.ENCNTR_ID = ENCNTR_ALIAS.ENCNTR_ID
	AND ENCNTR_ALIAS.ENCNTR_ALIAS_TYPE_CD = 619 -- FIN NBR
	AND DOSES.PERSON_ID = PERSON.PERSON_ID
	AND ORDERS.ORDER_ID = ORDER_DETAIL.ORDER_ID(+)
	AND ORDER_DETAIL.OE_FIELD_MEANING_ID(+) = 99 -- WEIGHT
	AND ORDER_DETAIL.ACTION_SEQUENCE(+) = 1
	AND ORDERS.ORDER_ID = OD_WT_UNITS.ORDER_ID(+)
	AND OD_WT_UNITS.OE_FIELD_MEANING_ID(+) = 100 -- WEIGHTUNIT
	AND OD_WT_UNITS.ACTION_SEQUENCE(+) = 1
GROUP BY
	MED_IDENTIFIER.VALUE,
	ENCOUNTER.LOC_NURSE_UNIT_CD,
	ENCNTR_ALIAS.ALIAS,
	PERSON.NAME_FULL_FORMATTED,
	ORDERS.ORDER_STATUS_CD,
	ORDER_DETAIL.OE_FIELD_DISPLAY_VALUE,
	OD_WT_UNITS.OE_FIELD_DISPLAY_VALUE