SELECT DISTINCT
	ORDERS.ENCNTR_ID,
	ORDERS.ORDER_ID,
	pi_get_cv_display(ORDERS.CATALOG_CD) AS MED,
	ORDERS.ORDERED_AS_MNEMONIC AS MNEMONIC,
	PRSNL.NAME_FULL_FORMATTED AS PROVIDER,
	pi_get_cv_display(PRSNL.POSITION_CD) AS PROVIDER_POSITION,
	pi_get_cv_display(ENCNTR_LOC_HIST.LOC_FACILITY_CD) AS FACILITY,
	pi_get_cv_display(ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD) AS NURSE_UNIT
FROM
	ENCNTR_LOC_HIST,
	ORDER_ACTION,
	ORDERS,
	PRSNL
WHERE
	ORDERS.CATALOG_CD = 9908146 -- ethanol
	AND ORDERS.CATALOG_TYPE_CD = 1363 -- Pharmacy
	-- AND ORDERS.ORIG_ORD_AS_FLAG = 0
	-- AND	ORDERS.TEMPLATE_ORDER_FLAG IN (0, 1)
	AND ORDERS.ORIG_ORDER_DT_TM BETWEEN
		pi_to_gmt(
			TO_DATE(
				@Prompt('Enter begin date', 'D', , mono, free, persistent, {'12/01/2019 00:00:00'}, User:0), 
				pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
			), 
			'America/Chicago'
		)
		AND pi_to_gmt(
			TO_DATE(
				@Prompt('Enter end date', 'D', , mono, free, persistent, {'12/01/2020 00:00:00'}, User:1), 
				pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
			) - 1/86400, 
			'America/Chicago'
		)
	AND ORDERS.ENCNTR_ID = ENCNTR_LOC_HIST.ENCNTR_ID
	AND ENCNTR_LOC_HIST.BEG_EFFECTIVE_DT_TM <= ORDERS.ORIG_ORDER_DT_TM
	AND ENCNTR_LOC_HIST.TRANSACTION_DT_TM = (
		SELECT MAX(ELH.TRANSACTION_DT_TM)
		FROM ENCNTR_LOC_HIST ELH
		WHERE
			ORDERS.ENCNTR_ID = ELH.ENCNTR_ID
			AND ELH.TRANSACTION_DT_TM <= ORDERS.ORIG_ORDER_DT_TM
	)
	AND ENCNTR_LOC_HIST.LOC_FACILITY_CD IN (
		3310, -- HH HERMANN
		3796, -- HC Childrens
		3821, -- HH Clinics
		3822, -- HH Trans Care
		3823, -- HH Rehab
		1099966301 -- HH Oncology TMC		
	)
	AND ENCNTR_LOC_HIST.END_EFFECTIVE_DT_TM >= ORDERS.ORIG_ORDER_DT_TM
	AND ORDERS.ORDER_ID = ORDER_ACTION.ORDER_ID
	AND ORDER_ACTION.ACTION_TYPE_CD = 1376 -- Order
	AND ORDER_ACTION.ORDER_PROVIDER_ID = PRSNL.PERSON_ID

