WITH CURR_PTS AS (
	SELECT DISTINCT
		ENCNTR_DOMAIN.ENCNTR_ID,
		ENCNTR_DOMAIN.PERSON_ID
	FROM
		ENCNTR_DOMAIN
	WHERE
		ENCNTR_DOMAIN.LOC_NURSE_UNIT_CD IN (
			3861, -- HH 5WCP
			3921, -- HH 5ECP
			3955, -- HH 4WCP
			8667250, -- HH MIMU
			265179687, -- HH ACE
			1846341943, -- HH 3CP
			1846342787, -- HH 3CIM
			3393773579 -- HH 2CC
		)
		AND ENCNTR_DOMAIN.END_EFFECTIVE_DT_TM > DATE '2099-12-31'
), LOC_HIST AS (
	SELECT DISTINCT
		ENCNTR_LOC_HIST.ENCNTR_ID,
		CURR_PTS.PERSON_ID,
		ENCNTR_LOC_HIST.ENCNTR_LOC_HIST_ID AS ELH_ID,
		ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD,
		ENCNTR_LOC_HIST.BEG_EFFECTIVE_DT_TM,
		ENCNTR_LOC_HIST.END_EFFECTIVE_DT_TM,
		ENCNTR_LOC_HIST.END_EFFECTIVE_DT_TM - ENCNTR_LOC_HIST.BEG_EFFECTIVE_DT_TM AS TRNS_DURATION,
		CASE
			WHEN 
				LAG(ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD, 1, 0) OVER (
					PARTITION BY ENCNTR_LOC_HIST.ENCNTR_ID 
					ORDER BY ENCNTR_LOC_HIST.ENCNTR_LOC_HIST_ID
				) <> ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD THEN 1
			ELSE 0
		END AS TRANSFER_IN,
		CASE
			WHEN
				LEAD(ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD, 1, 0) OVER (
					PARTITION BY ENCNTR_LOC_HIST.ENCNTR_ID 
					ORDER BY ENCNTR_LOC_HIST.ENCNTR_LOC_HIST_ID
				) <> ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD THEN -1
			ELSE 0
		END AS TRANSFER_OUT
	FROM
		CURR_PTS,
		ENCNTR_LOC_HIST
	WHERE
		CURR_PTS.ENCNTR_ID = ENCNTR_LOC_HIST.ENCNTR_ID
), LOC_GROUP AS (
	SELECT DISTINCT
		LOC_HIST.ENCNTR_ID,
		LOC_HIST.PERSON_ID,
		LOC_HIST.ELH_ID,
		LOC_HIST.BEG_EFFECTIVE_DT_TM,
		LOC_HIST.END_EFFECTIVE_DT_TM,
		LOC_HIST.LOC_NURSE_UNIT_CD,
		SUM(LOC_HIST.TRANSFER_IN) OVER (PARTITION BY LOC_HIST.ENCNTR_ID ORDER BY LOC_HIST.ELH_ID) AS TRNS_GROUP,
		LOC_HIST.TRNS_DURATION
	FROM
		LOC_HIST
), LOC_LIST AS (
	SELECT DISTINCT
		LOC_GROUP.ENCNTR_ID,
		LOC_GROUP.PERSON_ID,
		LOC_GROUP.TRNS_GROUP AS LOC_ORDER,
		LOC_GROUP.LOC_NURSE_UNIT_CD,
--		pi_get_cv_display(LOC_GROUP.LOC_NURSE_UNIT_CD) AS NURSE_UNIT,
		MIN(LOC_GROUP.BEG_EFFECTIVE_DT_TM) AS BEG_EFFECTIVE_DT_TM,
		MAX(LOC_GROUP.END_EFFECTIVE_DT_TM) AS END_EFFECTIVE_DT_TM,
--		pi_from_gmt(MIN(LOC_GROUP.BEG_EFFECTIVE_DT_TM), 'America/Chicago') AS ARRIVE_DATETIME,
		SUM(LOC_GROUP.TRNS_DURATION) AS TRNS_DURATION
	FROM
		LOC_GROUP
	GROUP BY
		LOC_GROUP.ENCNTR_ID,
		LOC_GROUP.PERSON_ID,
		LOC_GROUP.TRNS_GROUP,
		LOC_GROUP.LOC_NURSE_UNIT_CD
), PREV_UNIT AS (
	SELECT DISTINCT
		LOC_LIST.ENCNTR_ID,
		LOC_LIST.PERSON_ID,
		LAG(LOC_LIST.LOC_NURSE_UNIT_CD, 1, 0) OVER (PARTITION BY LOC_LIST.ENCNTR_ID ORDER BY LOC_LIST.LOC_ORDER) AS PREV_NURSE_UNIT_CD,
		LOC_LIST.LOC_NURSE_UNIT_CD,
		LOC_LIST.BEG_EFFECTIVE_DT_TM
	FROM
		LOC_LIST
)

SELECT DISTINCT
	ENCNTR_ALIAS.ALIAS AS FIN,
    PERSON.NAME_FULL_FORMATTED AS NAME,
	pi_from_gmt(PREV_UNIT.BEG_EFFECTIVE_DT_TM, 'America/Chicago') AS TRANSFER_DATETIME,
	pi_get_cv_display(PREV_UNIT.PREV_NURSE_UNIT_CD) AS TRANSFER_FROM,
	pi_get_cv_display(ENCNTR_DOMAIN.LOC_NURSE_UNIT_CD) AS TRANSFER_TO,
	pi_get_cv_display(ENCNTR_DOMAIN.LOC_ROOM_CD) AS ROOM
FROM
	ENCNTR_ALIAS,
	ENCNTR_DOMAIN,
	PERSON,
	PREV_UNIT
WHERE
	PREV_UNIT.LOC_NURSE_UNIT_CD IN (
		3861, -- HH 5WCP
		3921, -- HH 5ECP
		3955, -- HH 4WCP
		8667250, -- HH MIMU
		265179687, -- HH ACE
		1846341943, -- HH 3CP
		1846342787, -- HH 3CIM
		3393773579 -- HH 2CC
	)
	AND PREV_UNIT.PREV_NURSE_UNIT_CD IN (
		4122, -- HH MICU
		4137, -- HH CCU
		5441, -- HH STIC
		5541, -- HH CVICU
		18116572, -- HH 8WJP
		283905037, -- HH 7J
		1993318732, -- HH HFIC
		2369096643, -- HH TSCU
		2041371668, -- HH NVIC
		3311213379, -- HH TICU
		3224987721, -- HH S STIC
		3224986803, -- HH S BURN
		3224988589, -- HH S SHIC
		3224988925, -- HH S TSIC
		3392290381 -- HH S MICU
	)
	AND PREV_UNIT.BEG_EFFECTIVE_DT_TM BETWEEN
		pi_to_gmt(TRUNC(SYSDATE) - 1, 'America/Chicago')
		AND pi_to_gmt(TRUNC(SYSDATE) - 1/86400, 'America/Chicago')
	AND PREV_UNIT.ENCNTR_ID = ENCNTR_ALIAS.ENCNTR_ID
	AND ENCNTR_ALIAS.ENCNTR_ALIAS_TYPE_CD = 619 -- FIN NBR
	AND PREV_UNIT.ENCNTR_ID = ENCNTR_DOMAIN.ENCNTR_ID
	AND PREV_UNIT.PERSON_ID = PERSON.PERSON_ID