WITH PATIENTS AS (
	SELECT DISTINCT
		ENCOUNTER.ENCNTR_ID,
		-- PERSON.PERSON_ID,
		ENCNTR_ALIAS.ALIAS AS FIN,
		PERSON.NAME_FULL_FORMATTED AS NAME,
		TRUNC(((pi_from_gmt(ENCOUNTER.REG_DT_TM, 'America/Chicago')) - PERSON.BIRTH_DT_TM) / 365.25, 0) AS AGE,
		pi_get_cv_display(ENCOUNTER.LOC_NURSE_UNIT_CD) AS NURSE_UNIT,
		pi_get_cv_display(ENCOUNTER.LOC_ROOM_CD) AS ROOM,
		pi_get_cv_display(ENCOUNTER.LOC_BED_CD) AS BED,
		PRSNL.NAME_FULL_FORMATTED AS ATTENDING,
		pi_from_gmt(ENCOUNTER.REG_DT_TM, 'America/Chicago') AS ADMIT_DATETIME,
		ENCOUNTER.REASON_FOR_VISIT
	FROM
		ENCNTR_ALIAS,
		ENCNTR_DOMAIN,
		ENCNTR_PRSNL_RELTN,
		ENCOUNTER,
		PERSON,
		PRSNL
	WHERE
		ENCNTR_DOMAIN.LOC_FACILITY_CD IN (
			3310, -- HH HERMANN
			3796, -- HC Childrens
			-- 3821, -- HH Clinics
			3822, -- HH Trans Care
			3823 -- HH Rehab
			-- 1099966301, -- HH Oncology TMC
		)
		AND ENCNTR_DOMAIN.ENCNTR_ID = ENCOUNTER.ENCNTR_ID
		AND ENCOUNTER.REG_DT_TM BETWEEN
			DECODE(
				@Prompt('Choose date range', 'A', {'Yesterday', 'User-defined'}, mono, free, , , User:0),
				'Yesterday', pi_to_gmt(TRUNC(SYSDATE) - 1, 'America/Chicago'),
				'User-defined', pi_to_gmt(
					TO_DATE(
						@Prompt('Enter begin date', 'D', , mono, free, persistent, {'05/01/2021 00:00:00'}, User:1),
						pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
					),
					pi_time_zone(1, 'America/Chicago')
				)
			)
			AND DECODE(
				@Prompt('Choose date range', 'A', {'Yesterday', 'User-defined'}, mono, free, , , User:0),
				'Yesterday', pi_to_gmt(TRUNC(SYSDATE) - 1/86400, 'America/Chicago'),
				'User-defined', pi_to_gmt(
					TO_DATE(
						@Prompt('Enter end date', 'D', , mono, free, persistent, {'05/01/2022 00:00:00'}, User:2),
						pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
					) - 1/86400,
					pi_time_zone(1, 'America/Chicago')
				)
			)		
		AND ENCOUNTER.DISCH_DT_TM IS NULL
		AND ENCOUNTER.ENCNTR_TYPE_CLASS_CD IN (
			42631 -- Inpatient
			-- 55851, -- Emergency
			-- 688523 -- Observation
		)
		AND ENCOUNTER.PERSON_ID = PERSON.PERSON_ID
		AND TRUNC(((pi_from_gmt(ENCOUNTER.REG_DT_TM, 'America/Chicago')) - PERSON.BIRTH_DT_TM) / 365.25, 0) > 1
		AND ENCNTR_DOMAIN.ENCNTR_ID = ENCNTR_PRSNL_RELTN.ENCNTR_ID
		AND ENCNTR_PRSNL_RELTN.EXPIRATION_IND = 0
		AND ENCNTR_PRSNL_RELTN.ENCNTR_PRSNL_R_CD = 368029 -- Physician Attending
		AND ENCNTR_PRSNL_RELTN.END_EFFECTIVE_DT_TM > DATE '2099-12-31'
		AND ENCNTR_PRSNL_RELTN.PRSNL_PERSON_ID = PRSNL.PERSON_ID
		AND ENCNTR_DOMAIN.ENCNTR_ID = ENCNTR_ALIAS.ENCNTR_ID
		AND ENCNTR_ALIAS.ENCNTR_ALIAS_TYPE_CD = 619 -- FIN NBR
		AND ENCNTR_ALIAS.ACTIVE_IND = 1
), ADMIT_DIAGNOSIS AS (
	SELECT DISTINCT
		PATIENTS.ENCNTR_ID,
		NOMENCLATURE.SOURCE_IDENTIFIER AS ICD_10_CODE,
		NOMENCLATURE.SOURCE_STRING AS DIAGNOSIS
		-- DIAGNOSIS.DIAG_TYPE_CD,
		-- pi_get_cv_display(DIAGNOSIS.DIAG_TYPE_CD) AS DIAG_TYPE,
		-- pi_from_gmt(DIAGNOSIS.BEG_EFFECTIVE_DT_TM, 'America/Chicago') AS BEGIN_DATETIME,
		-- pi_from_gmt(DIAGNOSIS.END_EFFECTIVE_DT_TM, 'America/Chicago') AS END_DATETIME,
		-- pi_from_gmt(DIAGNOSIS.UPDT_DT_TM, 'America/Chicago') AS UPDATE_DATETIME
	FROM
		DIAGNOSIS,
		NOMENCLATURE,
		PATIENTS
	WHERE
		PATIENTS.ENCNTR_ID = DIAGNOSIS.ENCNTR_ID
		AND DIAGNOSIS.DIAG_TYPE_CD = 509164 -- Admitting
		-- AND DIAGNOSIS.DIAG_PRIORITY = 1
		AND DIAGNOSIS.NOMENCLATURE_ID = NOMENCLATURE.NOMENCLATURE_ID
		-- AND REGEXP_INSTR(NOMENCLATURE.SOURCE_IDENTIFIER, '^A41.[4-9]|^T81.44X|^J44|^I50') > 0
		AND NOMENCLATURE.SOURCE_VOCABULARY_CD = 641836527 -- ICD-10-CM
		AND NOMENCLATURE.PRINCIPLE_TYPE_CD = 751 -- Disease or Syndrome	
), INSUR_PLANS AS (
	SELECT DISTINCT
		PATIENTS.ENCNTR_ID,
		ENCNTR_PLAN_RELTN.PRIORITY_SEQ,
		HEALTH_PLAN.PLAN_NAME
	FROM
		ENCNTR_PLAN_RELTN,
		HEALTH_PLAN,
		PATIENTS
	WHERE
		PATIENTS.ENCNTR_ID = ENCNTR_PLAN_RELTN.ENCNTR_ID
		-- AND ENCNTR_PLAN_RELTN.PRIORITY_SEQ = 1
		AND ENCNTR_PLAN_RELTN.END_EFFECTIVE_DT_TM > pi_to_gmt(SYSDATE, 'America/Chicago')
		AND ENCNTR_PLAN_RELTN.HEALTH_PLAN_ID = HEALTH_PLAN.HEALTH_PLAN_ID
), INSUR_ROLLUP AS (
	SELECT DISTINCT
		ENCNTR_ID,
		LISTAGG(PLAN_NAME, '; ') WITHIN GROUP (ORDER BY PRIORITY_SEQ) AS INSURANCE
	FROM
		INSUR_PLANS
	GROUP BY
		ENCNTR_ID
)

SELECT
	PATIENTS.*,
	ADMIT_DIAGNOSIS.ICD_10_CODE,
	ADMIT_DIAGNOSIS.DIAGNOSIS,
	INSUR_ROLLUP.INSURANCE
FROM
	ADMIT_DIAGNOSIS,
	INSUR_ROLLUP,
	PATIENTS
WHERE
	PATIENTS.ENCNTR_ID = INSUR_ROLLUP.ENCNTR_ID(+)
	AND PATIENTS.ENCNTR_ID = ADMIT_DIAGNOSIS.ENCNTR_ID(+)
	AND PATIENTS.NURSE_UNIT NOT IN ('HC NICE', 'HC NICW')

-- //clinisilonhh/PHI_Access$/PHI-HER - Pharmacy Adult/Meds to Bed/Daily Discharges
