SELECT DISTINCT
	CV_CLIN_EV.CODE_VALUE,
	CV_CLIN_EV.DISPLAY
FROM
	CODE_VALUE,
	CODE_VALUE CV_CLIN_EV,
	PI_THERA_CLASS_VIEW
WHERE
	PI_THERA_CLASS_VIEW.DRUG_CAT IN (
		'narcotic analgesic combinations', 
		'narcotic analgesics'
	)
	AND PI_THERA_CLASS_VIEW.DRUG_CAT_CD = CODE_VALUE.CODE_VALUE
	AND CODE_VALUE.DISPLAY_KEY = CV_CLIN_EV.DISPLAY_KEY
	AND CV_CLIN_EV.CODE_SET = 72
	