WITH ORD_ACTIONS AS (
	SELECT DISTINCT
		ORDER_ACTION.ORDER_ACTION_ID,
		ORDER_ACTION.ORDER_ID,
		ORDER_ACTION.ACTION_SEQUENCE,
		ORDER_ACTION.ACTION_TYPE_CD,
		ORDER_ACTION.ACTION_DT_TM,
		ORDERS.ENCNTR_ID
	FROM
		ORDER_ACTION,
		ORDERS
	WHERE
		ORDER_ACTION.ACTION_DT_TM BETWEEN
			pi_to_gmt(TRUNC(SYSDATE) - 2, pi_time_zone(2, @Variable('BOUSER')))
			AND pi_to_gmt(TRUNC(SYSDATE) - (1 / 86400), pi_time_zone(2, @Variable('BOUSER')))
		AND ORDER_ACTION.ORDER_ID = ORDERS.ORDER_ID
		AND ORDERS.CATALOG_TYPE_CD = 1363 -- Pharmacy
		AND ORDERS.ACTIVITY_TYPE_CD = 378 -- Pharmacy
), PTS AS (
	SELECT DISTINCT
		ORD_ACTIONS.ENCNTR_ID
	FROM
		ORD_ACTIONS
), TMC AS (
	SELECT DISTINCT
		PTS.ENCNTR_ID
	FROM
		ENCOUNTER,
		PTS
	WHERE
		PTS.ENCNTR_ID = ENCOUNTER.ENCNTR_ID
		AND ENCOUNTER.LOC_FACILITY_CD IN (
			3310, -- HH HERMANN
			3796, -- HC Childrens
			3821, -- HH Clinics
			3822, -- HH Trans Care
			3823, -- HH Rehab
			1099966301 -- HH Oncology TMC
		)
), REVIEWS AS (
	SELECT DISTINCT
		ORDER_REVIEW.REVIEW_DT_TM,
		PRSNL.NAME_FULL_FORMATTED,
		ORD_ACTIONS.ACTION_TYPE_CD
	FROM
		ORD_ACTIONS,
		ORDER_REVIEW,
		PRSNL,
		TMC
	WHERE
		ORD_ACTIONS.ENCNTR_ID = TMC.ENCNTR_ID
		AND ORD_ACTIONS.ORDER_ID = ORDER_REVIEW.ORDER_ID
		AND ORD_ACTIONS.ACTION_SEQUENCE = ORDER_REVIEW.ACTION_SEQUENCE
		AND ORDER_REVIEW.REVIEW_TYPE_FLAG = 3 -- Pharmacist
		AND ORDER_REVIEW.REVIEWED_STATUS_FLAG = 1
		AND ORDER_REVIEW.REVIEW_PERSONNEL_ID = PRSNL.PERSON_ID
), YEST_REVIEWS AS (
	SELECT DISTINCT
		pi_from_gmt(TRUNC(REVIEWS.REVIEW_DT_TM, 'HH'), (pi_time_zone(1, @Variable('BOUSER')))) AS REVIEW_HOUR,
		REVIEWS.NAME_FULL_FORMATTED AS PHARMACIST,
		pi_get_cv_display(REVIEWS.ACTION_TYPE_CD) AS ACTION_TYPE
	FROM
		REVIEWS
	WHERE
		REVIEWS.REVIEW_DT_TM BETWEEN
			pi_to_gmt(TRUNC(SYSDATE) - 1, pi_time_zone(2, @Variable('BOUSER')))
			AND pi_to_gmt(TRUNC(SYSDATE) - (1 / 86400), pi_time_zone(2, @Variable('BOUSER')))
)

SELECT *
FROM YEST_REVIEWS
PIVOT (
	COUNT(*) FOR ACTION_TYPE IN (
		'Order' ORDERED, 
		'Modify' MODIFIED, 
		'Discontinue' DISCONTINUED, 
		'Hold' HELD, 
		'Resume' RESUMED,
		'Reschedule' RESCHEDULED,
		'Renew' RENEWED,
		'Cancel' CANCELLED,
		'Complete' COMPLETED,
		'Delete' DELETED
	)
)

