SELECT DISTINCT
	pi_from_gmt(TRUNC(ORDER_REVIEW.REVIEW_DT_TM, 'HH'), (pi_time_zone(1, @Variable('BOUSER')))) AS REVIEW_HOUR,
	PRSNL.NAME_FULL_FORMATTED AS PHARMACIST,
	pi_get_cv_display(ORDER_ACTION.ACTION_TYPE_CD) AS ACTION_TYPE,
	COUNT(ORDERS.ORDER_ID) AS NUM_ACTIONS
FROM
	ENCOUNTER,
	ORDER_ACTION,
	ORDER_REVIEW,
	ORDERS,
	PRSNL
WHERE
	ORDERS.ORIG_ORDER_DT_TM BETWEEN
		pi_to_gmt(TRUNC(SYSDATE) - 1, pi_time_zone(2, @Variable('BOUSER')))
		AND pi_to_gmt(TRUNC(SYSDATE) - (1 / 86400), pi_time_zone(2, @Variable('BOUSER')))
	AND ORDERS.CATALOG_TYPE_CD = 1363 -- Pharmacy
	AND ORDERS.ACTIVITY_TYPE_CD = 378 -- Pharmacy
	AND ORDERS.ENCNTR_ID = ENCOUNTER.ENCNTR_ID
	AND ENCOUNTER.ORGANIZATION_ID = 1 -- Memorial Hermann Hospital
	AND ENCOUNTER.LOC_FACILITY_CD IN (
		3310, -- HH HERMANN
		3796, -- HC Childrens
		3821, -- HH Clinics
		3822, -- HH Trans Care
		3823, -- HH Rehab
		1099966301 -- HH Oncology TMC
	)
--	AND ORDERS.ORIG_ORD_AS_FLAG = 0 -- Normal Order
	AND ORDERS.ORDER_ID = ORDER_REVIEW.ORDER_ID
	AND ORDER_REVIEW.REVIEW_TYPE_FLAG = 3 -- Pharmacist
	AND ORDER_REVIEW.REVIEWED_STATUS_FLAG = 1
	AND ORDER_REVIEW.REVIEW_PERSONNEL_ID = PRSNL.PERSON_ID
	AND ORDER_REVIEW.ORDER_ID = ORDER_ACTION.ORDER_ID
	AND ORDER_REVIEW.ACTION_SEQUENCE = ORDER_ACTION.ACTION_SEQUENCE
	AND ORDER_ACTION.ACTION_TYPE_CD <> 1373 -- Complete
GROUP BY
	PRSNL.NAME_FULL_FORMATTED,
	ORDER_ACTION.ACTION_TYPE_CD,
	TRUNC(ORDER_REVIEW.REVIEW_DT_TM, 'HH')