WITH PROVIDER_ORDERS AS (
	SELECT DISTINCT
		ORDERS.ENCNTR_ID,
		ORDERS.ORDER_ID,
		ORDERS.ORIG_ORDER_DT_TM,
		ORDERS.CATALOG_CD,
		ORDER_ACTION.ORDER_ACTION_ID,
		ORDER_ACTION.ACTION_SEQUENCE,
		ORDER_ACTION.ACTION_TYPE_CD,
		ORDER_ACTION.COMMUNICATION_TYPE_CD,
		ORDER_ACTION.ACTION_DT_TM,
		ORDER_ACTION.ORDER_PROVIDER_ID,
		ORDER_ACTION.ACTION_PERSONNEL_ID,
		CASE
			WHEN ORDER_ACTION.ACTION_PERSONNEL_ID IN (94498610) THEN ORDER_ACTION.ACTION_PERSONNEL_ID
			WHEN ORDER_ACTION.ORDER_PROVIDER_ID IN (94498610) THEN ORDER_ACTION.ORDER_PROVIDER_ID
		END AS GRPBY_PROVIDER_ID
	FROM
		ENCNTR_LOC_HIST,
		ORDER_ACTION,
		ORDERS
	WHERE
		ORDER_ACTION.ACTION_DT_TM BETWEEN
		-- ORDERS.ORIG_ORDER_DT_TM BETWEEN
			DECODE(
				@Prompt('Choose date range', 'A', {'Last Month', 'User-defined'}, mono, free, , , User:0),
				'Last Month', pi_to_gmt(TRUNC(ADD_MONTHS(SYSDATE, -1), 'MONTH'), pi_time_zone(2, @Variable('BOUSER'))),
				'User-defined', pi_to_gmt(
					TO_DATE(
						@Prompt('Enter begin date', 'D', , mono, free, persistent, {'01/01/1800 00:00:00'}, User:1),
						pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
					),
					pi_time_zone(1, @Variable('BOUSER')))
			)
			AND DECODE(
				@Prompt('Choose date range', 'A', {'Last Month', 'User-defined'}, mono, free, , , User:79),
				'Last Month', pi_to_gmt(TRUNC(SYSDATE, 'MONTH') - 1/86400, pi_time_zone(2, @Variable('BOUSER'))),
				'User-defined', pi_to_gmt(
					TO_DATE(
						@Prompt('Enter end date', 'D', , mono, free, persistent, {'01/01/1800 23:59:59'}, User:2),
						pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
					),
					pi_time_zone(1, @Variable('BOUSER')))
			)
		AND ORDER_ACTION.ORDER_ID = ORDERS.ORDER_ID
		-- AND ORDER_ACTION.ORDER_PROVIDER_ID = ORDER_ACTION.ACTION_PERSONNEL_ID
		AND (
			ORDER_ACTION.ACTION_PERSONNEL_ID IN (94498610)
			OR (
				ORDER_ACTION.ORDER_PROVIDER_ID IN (94498610)
				AND ORDER_ACTION.COMMUNICATION_TYPE_CD = 95480246 -- eVerbal - Read Back
			)
		)
		-- AND ORDER_ACTION.ACTION_SEQUENCE = 1
		-- AND ORDER_ACTION.ACTION_TYPE_CD = 1376 -- Order
		AND ORDERS.ACTIVITY_TYPE_CD = 378 -- Pharmacy
		AND ORDERS.CATALOG_TYPE_CD = 1363 -- Pharmacy
		AND ORDERS.ENCNTR_ID = ENCNTR_LOC_HIST.ENCNTR_ID
		AND ENCNTR_LOC_HIST.BEG_EFFECTIVE_DT_TM <= ORDER_ACTION.ACTION_DT_TM
		AND ENCNTR_LOC_HIST.TRANSACTION_DT_TM = (
			SELECT MAX(ELH.TRANSACTION_DT_TM)
			FROM ENCNTR_LOC_HIST ELH
			WHERE
				ORDERS.ENCNTR_ID = ELH.ENCNTR_ID
				AND ELH.TRANSACTION_DT_TM <= ORDER_ACTION.ACTION_DT_TM
		)
		AND ENCNTR_LOC_HIST.END_EFFECTIVE_DT_TM >= ORDER_ACTION.ACTION_DT_TM
)

SELECT DISTINCT
	ENCNTR_ID,
	-- ORDER_ID,
	-- pi_from_gmt(ORIG_ORDER_DT_TM, (pi_time_zone(1, @Variable('BOUSER')))) AS ORDER_DATETIME,
	ORDER_ACTION_ID,
	-- pi_from_gmt(ACTION_DT_TM, (pi_time_zone(1, @Variable('BOUSER')))) AS ACTION_DATETIME,
	-- pi_get_cv_display(CATALOG_CD) AS MEDICATION,
	-- ACTION_SEQUENCE,
	pi_get_cv_display(ACTION_TYPE_CD) AS ACTION_TYPE,
	pi_get_cv_display(COMMUNICATION_TYPE_CD) AS COMM_TYPE,
	-- ORDER_PROVIDER_ID,
	PRSNL_PROVIDER.NAME_FULL_FORMATTED AS PROVIDER,
	-- ACTION_PERSONNEL_ID,
	PRSNL_ACTION.NAME_FULL_FORMATTED AS ACTION_BY,
	PRSNL_GRPBY_PROVIDER.NAME_FULL_FORMATTED AS GRPBY_PROVIDER
FROM 
	PROVIDER_ORDERS,
	PRSNL PRSNL_ACTION,
	PRSNL PRSNL_GRPBY_PROVIDER,
	PRSNL PRSNL_PROVIDER
WHERE
	PROVIDER_ORDERS.ORDER_PROVIDER_ID = PRSNL_PROVIDER.PERSON_ID
	AND PROVIDER_ORDERS.ACTION_PERSONNEL_ID = PRSNL_ACTION.PERSON_ID
	AND PROVIDER_ORDERS.GRPBY_PROVIDER_ID = PRSNL_GRPBY_PROVIDER.PERSON_ID