WITH PATIENTS AS (
	SELECT DISTINCT
		ENCOUNTER.ENCNTR_ID,
		ENCOUNTER.PERSON_ID,
		ENCNTR_ALIAS.ALIAS AS FIN
	FROM
		ENCNTR_ALIAS,
		ENCOUNTER
	WHERE
	    ENCNTR_ALIAS.ALIAS IN @prompt('Enter value(s) for Alias','A',,Multi,Free,Persistent,,User:0)
		AND ENCNTR_ALIAS.ENCNTR_ALIAS_TYPE_CD = 619 -- FIN NBR
		AND ENCNTR_ALIAS.ACTIVE_IND = 1
		AND ENCNTR_ALIAS.ENCNTR_ID = ENCOUNTER.ENCNTR_ID
), DOSES AS (
	SELECT DISTINCT
		PATIENTS.ENCNTR_ID,
		PATIENTS.FIN,
		CASE
			WHEN ORDERS.TEMPLATE_ORDER_ID = 0 THEN ORDERS.ORDER_ID
			ELSE ORDERS.TEMPLATE_ORDER_ID
		END AS ORIG_ORDER_ID,
		-- CLINICAL_EVENT.EVENT_END_DT_TM,
		pi_from_gmt(CLINICAL_EVENT.EVENT_END_DT_TM, 'America/Chicago') AS MED_DATETIME,
		CLINICAL_EVENT.EVENT_ID,
		pi_get_cv_display(CLINICAL_EVENT.EVENT_CD) AS MEDICATION,
		CE_MED_RESULT.ADMIN_DOSAGE,
		pi_get_cv_display(CE_MED_RESULT.DOSAGE_UNIT_CD) AS DOSAGE_UNIT,
		-- CE_MED_RESULT.INFUSION_RATE,
		-- pi_get_cv_display(CE_MED_RESULT.INFUSION_UNIT_CD) AS INFUSION_UNIT,
		pi_get_cv_display(CE_MED_RESULT.ADMIN_ROUTE_CD) AS ADMIN_ROUTE,
		-- pi_get_cv_display(CE_MED_RESULT.IV_EVENT_CD) AS IV_EVENT,
		pi_get_cv_display(ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD) AS NURSE_UNIT
	FROM
		CE_MED_RESULT,
		CLINICAL_EVENT,
		ENCNTR_LOC_HIST,
		ORDERS,
		PATIENTS
	WHERE
		PATIENTS.ENCNTR_ID = CLINICAL_EVENT.ENCNTR_ID
		AND CLINICAL_EVENT.EVENT_CLASS_CD = 158 -- MED
		AND PATIENTS.PERSON_ID = CLINICAL_EVENT.PERSON_ID
		AND CLINICAL_EVENT.EVENT_CD IN (
			37556956, --FENTanyl
			37557589, -- midazolam
			37557998 -- rocuronium
		)
		AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
		AND CLINICAL_EVENT.EVENT_ID = CE_MED_RESULT.EVENT_ID
		AND CE_MED_RESULT.IV_EVENT_CD = 0
		AND CE_MED_RESULT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
		AND CLINICAL_EVENT.ENCNTR_ID = ENCNTR_LOC_HIST.ENCNTR_ID
		AND ENCNTR_LOC_HIST.BEG_EFFECTIVE_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
		AND ENCNTR_LOC_HIST.TRANSACTION_DT_TM = (
			SELECT MAX(ELH.TRANSACTION_DT_TM)
			FROM ENCNTR_LOC_HIST ELH
			WHERE
				CLINICAL_EVENT.ENCNTR_ID = ELH.ENCNTR_ID
				AND ELH.TRANSACTION_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
		)
		AND ENCNTR_LOC_HIST.END_EFFECTIVE_DT_TM >= CLINICAL_EVENT.EVENT_END_DT_TM
		AND CLINICAL_EVENT.ORDER_ID = ORDERS.ORDER_ID
), DOSE_ORDERS AS (
	SELECT DISTINCT
		DOSES.*,
		pi_from_gmt(ORDERS.ORIG_ORDER_DT_TM, 'America/Chicago') AS ORDER_DATETIME,
		pi_from_gmt(ORDER_REVIEW.REVIEW_DT_TM, 'America/Chicago') AS VERIFY_DATETIME
	FROM
		DOSES,
		ORDERS,
		ORDER_REVIEW
	WHERE
		DOSES.ORIG_ORDER_ID = ORDERS.ORDER_ID
		AND ORDERS.ORDER_ID = ORDER_REVIEW.ORDER_ID(+)
		AND ORDER_REVIEW.ACTION_SEQUENCE(+) = 1
		AND ORDER_REVIEW.REVIEW_TYPE_FLAG(+) = 3
		AND ORDER_REVIEW.REVIEWED_STATUS_FLAG(+) IN (1, 5)	
)

SELECT DISTINCT
	DOSE_ORDERS.*,
	ORDER_PRODUCT.ITEM_ID,
	MED_IDENTIFIER.VALUE AS MED_PRODUCT,		
	ORDER_PRODUCT.DOSE_QUANTITY,
	pi_get_cv_display(ORDER_PRODUCT.DOSE_QUANTITY_UNIT_CD) AS DOSE_QUANTITY_UNIT
FROM
	DOSE_ORDERS,
	MED_IDENTIFIER,
	ORDER_PRODUCT
WHERE
	DOSE_ORDERS.ORIG_ORDER_ID = ORDER_PRODUCT.ORDER_ID(+)
	-- AND ORDER_PRODUCT.ACTION_SEQUENCE = 1
	AND ORDER_PRODUCT.INGRED_SEQUENCE(+) = 1
	AND ORDER_PRODUCT.ITEM_ID = MED_IDENTIFIER.ITEM_ID(+)
	AND MED_IDENTIFIER.MED_IDENTIFIER_TYPE_CD(+) = 1564 -- Generic Name
	-- AND MED_IDENTIFIER.MED_IDENTIFIER_TYPE_CD = 1563 -- Charge Number (CDM)
	AND MED_IDENTIFIER.MED_PRODUCT_ID(+) = 0
