WITH DOSES AS (
	SELECT DISTINCT
		CLINICAL_EVENT.ENCNTR_ID,
		CLINICAL_EVENT.PERSON_ID,
		CLINICAL_EVENT.EVENT_END_DT_TM,
		pi_from_gmt(CLINICAL_EVENT.EVENT_END_DT_TM, 'America/Chicago') AS DOSE_DATETIME,
		CLINICAL_EVENT.EVENT_ID,
		CLINICAL_EVENT.EVENT_CD,
		LOWER(pi_get_cv_display(CLINICAL_EVENT.EVENT_CD)) AS MEDICATION,
		CLINICAL_EVENT.ORDER_ID,
		CE_MED_RESULT.ADMIN_DOSAGE,
		CE_MED_RESULT.DOSAGE_UNIT_CD,
		pi_get_cv_display(CE_MED_RESULT.DOSAGE_UNIT_CD) AS DOSAGE_UNIT,
		CE_MED_RESULT.INFUSION_RATE,
		CE_MED_RESULT.INFUSION_UNIT_CD,
		pi_get_cv_display(CE_MED_RESULT.INFUSION_UNIT_CD) AS INFUSION_UNIT,
		CE_MED_RESULT.IV_EVENT_CD,
		pi_get_cv_display(CE_MED_RESULT.IV_EVENT_CD) AS IV_EVENT,
		ENCNTR_LOC_HIST.LOC_FACILITY_CD,
		pi_get_cv_display(ENCNTR_LOC_HIST.LOC_FACILITY_CD) AS FACILITY,
		ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD,
		pi_get_cv_display(ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD) AS NURSE_UNIT
	FROM
		CE_MED_RESULT,
		CLINICAL_EVENT,
		ENCNTR_LOC_HIST
	WHERE
		CLINICAL_EVENT.EVENT_CD IN (
			37557367, -- ketamine
			37556709, -- dexmedetomidine
			37556956, -- FENTanyl
			37557204, -- HYDROmorphone
			37557620, -- morphine Sulfate
			37557455, -- LORAzepam
			37557589, -- midazolam
			37557925 -- propofol
		)
		AND CLINICAL_EVENT.EVENT_END_DT_TM BETWEEN
			pi_to_gmt(SYSDATE - 1, 'America/Chicago')
			AND pi_to_gmt(SYSDATE, 'America/Chicago')
		AND CLINICAL_EVENT.EVENT_ID = CE_MED_RESULT.EVENT_ID
		AND CE_MED_RESULT.IV_EVENT_CD > 0
		AND CLINICAL_EVENT.ENCNTR_ID = ENCNTR_LOC_HIST.ENCNTR_ID
		AND ENCNTR_LOC_HIST.BEG_EFFECTIVE_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
		AND ENCNTR_LOC_HIST.TRANSACTION_DT_TM = (
			SELECT MAX(ELH.TRANSACTION_DT_TM)
			FROM ENCNTR_LOC_HIST ELH
			WHERE
				CLINICAL_EVENT.ENCNTR_ID = ELH.ENCNTR_ID
				AND ELH.TRANSACTION_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
		)
		AND ENCNTR_LOC_HIST.END_EFFECTIVE_DT_TM >= CLINICAL_EVENT.EVENT_END_DT_TM
		AND ENCNTR_LOC_HIST.LOC_FACILITY_CD IN (
			3310, -- HH HERMANN
			-- 3796, -- HC Childrens
			3821, -- HH Clinics
			3822, -- HH Trans Care
			3823 -- HH Rehab		
		)
), ACTIONS AS (
	SELECT
		DOSES.ENCNTR_ID,
		DOSES.EVENT_ID,
		DOSES.ORDER_ID,
		MAX(ORDER_ACTION.ACTION_SEQUENCE) AS ACTION_SEQUENCE
	FROM
		DOSES,
		ORDER_ACTION
	WHERE
		DOSES.ORDER_ID = ORDER_ACTION.ORDER_ID
		AND ORDER_ACTION.ACTION_DT_TM < DOSES.EVENT_END_DT_TM
	GROUP BY
		DOSES.ENCNTR_ID,
		DOSES.EVENT_ID,
		DOSES.ORDER_ID
), MED_PRODS AS (
	SELECT
		ACTIONS.ENCNTR_ID,
		ACTIONS.EVENT_ID,
		ACTIONS.ORDER_ID,
		ACTIONS.ACTION_SEQUENCE,
		ORDER_PRODUCT.ITEM_ID
	FROM
		ACTIONS,
		ORDER_PRODUCT
	WHERE
		ACTIONS.ORDER_ID = ORDER_PRODUCT.ORDER_ID
		AND ACTIONS.ACTION_SEQUENCE = ORDER_PRODUCT.ACTION_SEQUENCE
		AND ORDER_PRODUCT.ITEM_ID IN (
			275733495, -- ketAMINE 10 mg/mL in NS 50 mL syringe
			2931843, -- ketAMINE 500 mg/10 ml INJ VL
			10880895, -- fentaNYL 1000microgram/20ml drip (pyxis)
			117052454, -- dexmedetomidine 4 microgram/ml 100ml
			2950132, -- dexmedetomidine 200 microgram/2ml INJ
			2954763, -- propofol 1000 mg/100 ml INJ
			2902310, -- propofol 500 mg/50 ml INJ
			10881130, -- midazolam 50mg/ NS 50ml drip (premixed)
			107511585, -- HYDROmorphone HCL 50mg in NS 50ml PF
			10881363, -- MORPhine Sulfate 50mg/ NS 50ml drip (pyxis)
			72418593 -- LORazepam 50mg/NS 50ml Drip
		) 
), LAST_CHARTED AS (
	SELECT DISTINCT
		DOSES.ENCNTR_ID,
		MED_PRODS.ITEM_ID,
		MAX(DOSES.EVENT_END_DT_TM) AS LAST_CHARTED_DT_TM
	FROM
		DOSES,
		MED_PRODS
	WHERE
		DOSES.EVENT_ID = MED_PRODS.EVENT_ID
		AND (
			DOSES.ADMIN_DOSAGE > 0
			OR DOSES.IV_EVENT_CD IN (
				688706, -- Begin Bag
				688709 -- Rate Change
			)
		)
	GROUP BY 
		DOSES.ENCNTR_ID,
		MED_PRODS.ITEM_ID
), BAGS_YESTERDAY AS (
	SELECT DISTINCT
		DOSES.ENCNTR_ID,
		DOSES.EVENT_CD,
		COUNT(DOSES.EVENT_ID) AS BAGS_LAST_24H
	FROM
		DOSES
	WHERE
		DOSES.IV_EVENT_CD = 688706 -- Begin Bag
	GROUP BY 
		DOSES.ENCNTR_ID,
		DOSES.EVENT_CD
)

SELECT DISTINCT
	DOSES.EVENT_CD,
	DOSES.MEDICATION,
	MED_PRODS.ITEM_ID,
	-- MAX(MED_IDENTIFIER.VALUE) KEEP (DENSE_RANK LAST ORDER BY DOSES.ACTION_SEQUENCE) AS MED_PRODUCT, 
	MED_IDENTIFIER.VALUE AS MED_PRODUCT,
	pi_get_cv_display(ENCOUNTER.LOC_NURSE_UNIT_CD) AS CURRENT_NURSE_UNIT,
	pi_get_cv_display(ENCOUNTER.LOC_ROOM_CD) AS ROOM,
	pi_get_cv_display(ENCOUNTER.LOC_BED_CD) AS BED,
	ENCNTR_ALIAS.ALIAS AS FIN,
	PERSON.NAME_FULL_FORMATTED AS NAME,
	--pi_from_gmt(MAX(DOSES.EVENT_END_DT_TM), 'America/Chicago') AS LAST_RATE_DATETIME,
	pi_from_gmt(ORDERS.ORIG_ORDER_DT_TM, 'America/Chicago') AS ORDER_DATETIME,
	pi_from_gmt(LAST_CHARTED.LAST_CHARTED_DT_TM, 'America/Chicago') AS LAST_CHARTED_DATETIME,
	LAST_CHARTED.LAST_CHARTED_DT_TM - ORDERS.ORIG_ORDER_DT_TM AS DURATION,
	MAX(DOSES.INFUSION_RATE) KEEP (DENSE_RANK LAST ORDER BY DOSES.EVENT_END_DT_TM) AS RATE, 
	MAX(DOSES.INFUSION_UNIT_CD) KEEP (DENSE_RANK LAST ORDER BY DOSES.EVENT_END_DT_TM) AS RATE_UNIT_CD,
	pi_get_cv_display(MAX(DOSES.INFUSION_UNIT_CD) KEEP (DENSE_RANK LAST ORDER BY DOSES.EVENT_END_DT_TM)) AS RATE_UNITS,
	ORDER_DETAIL.OE_FIELD_DISPLAY_VALUE AS WEIGHT,
	OD_WT_UNITS.OE_FIELD_DISPLAY_VALUE AS WEIGHT_UNITS,
	MED_DISPENSE.STRENGTH,
	MED_DISPENSE.STRENGTH_UNIT_CD,
	pi_get_cv_display(MED_DISPENSE.STRENGTH_UNIT_CD) AS STRENGTH_UNITS,
	MED_DISPENSE.VOLUME,
	MED_DISPENSE.VOLUME_UNIT_CD,
	pi_get_cv_display(MED_DISPENSE.VOLUME_UNIT_CD) AS VOLUME_UNITS,
	BAGS_YESTERDAY.BAGS_LAST_24H,
	CASE
		WHEN MAX(DOSES.INFUSION_RATE) KEEP (DENSE_RANK LAST ORDER BY DOSES.EVENT_END_DT_TM) = 0 THEN 'No'
		WHEN DOSES.MEDICATION = 'fentanyl' AND MAX(DOSES.INFUSION_RATE) KEEP (DENSE_RANK LAST ORDER BY DOSES.EVENT_END_DT_TM) > 100 THEN 'Yes'
		WHEN DOSES.MEDICATION = 'hydromorphone' AND MAX(DOSES.INFUSION_RATE) KEEP (DENSE_RANK LAST ORDER BY DOSES.EVENT_END_DT_TM) > 2 THEN 'Yes'
		WHEN DOSES.MEDICATION = 'midazolam' AND MAX(DOSES.INFUSION_RATE) KEEP (DENSE_RANK LAST ORDER BY DOSES.EVENT_END_DT_TM) > 4 THEN 'Yes'
		WHEN DOSES.MEDICATION = 'lorazepam' AND MAX(DOSES.INFUSION_RATE) KEEP (DENSE_RANK LAST ORDER BY DOSES.EVENT_END_DT_TM) > 2 THEN 'Yes'
		WHEN DOSES.MEDICATION = 'ketamine' AND MAX(DOSES.INFUSION_RATE) KEEP (DENSE_RANK LAST ORDER BY DOSES.EVENT_END_DT_TM) > 2 THEN 'Yes'
		WHEN DOSES.MEDICATION = 'propofol' AND (
			MAX(DOSES.INFUSION_RATE) KEEP (DENSE_RANK LAST ORDER BY DOSES.EVENT_END_DT_TM) > 20 
			OR LAST_CHARTED.LAST_CHARTED_DT_TM - ORDERS.ORIG_ORDER_DT_TM > 2
		) THEN 'Yes'
		WHEN DOSES.MEDICATION = 'dexmedetomidine' AND LAST_CHARTED.LAST_CHARTED_DT_TM - ORDERS.ORIG_ORDER_DT_TM > 1 THEN 'Yes'
		ELSE 'No'
	END AS FLAG_DRIP
FROM
	BAGS_YESTERDAY,
	DOSES,
	ENCNTR_ALIAS,
	ENCOUNTER,
	LAST_CHARTED,
	MED_DISPENSE,
	MED_IDENTIFIER,
	MED_PRODS,
	ORDER_DETAIL,
	ORDER_DETAIL OD_WT_UNITS,
	ORDERS,
	PERSON
WHERE
	DOSES.EVENT_ID = MED_PRODS.EVENT_ID
	AND MED_PRODS.ITEM_ID = MED_IDENTIFIER.ITEM_ID
	AND MED_IDENTIFIER.MED_IDENTIFIER_TYPE_CD = 1564 -- Description
	AND MED_IDENTIFIER.MED_PRODUCT_ID = 0
	AND MED_PRODS.ITEM_ID = MED_DISPENSE.ITEM_ID
	AND DOSES.ENCNTR_ID = LAST_CHARTED.ENCNTR_ID
	AND MED_PRODS.ITEM_ID = LAST_CHARTED.ITEM_ID
	AND DOSES.ENCNTR_ID = BAGS_YESTERDAY.ENCNTR_ID
	AND DOSES.EVENT_CD = BAGS_YESTERDAY.EVENT_CD
	--AND DOSES.ITEM_ID = BAGS_YESTERDAY.ITEM_ID
	AND DOSES.IV_EVENT_CD IN (
		688706, -- Begin Bag
		688709 -- Rate Change
	)
	AND DOSES.ORDER_ID = ORDERS.ORDER_ID
	AND ORDERS.ORDER_STATUS_CD = 1386 -- Ordered
	AND DOSES.ENCNTR_ID = ENCOUNTER.ENCNTR_ID
	AND DOSES.ENCNTR_ID = ENCNTR_ALIAS.ENCNTR_ID
	AND ENCNTR_ALIAS.ENCNTR_ALIAS_TYPE_CD = 619 -- FIN NBR
	AND DOSES.PERSON_ID = PERSON.PERSON_ID
	AND ORDERS.ORDER_ID = ORDER_DETAIL.ORDER_ID(+)
	AND ORDER_DETAIL.OE_FIELD_MEANING_ID(+) = 99 -- WEIGHT
	AND ORDER_DETAIL.ACTION_SEQUENCE(+) = 1
	AND ORDERS.ORDER_ID = OD_WT_UNITS.ORDER_ID(+)
	AND OD_WT_UNITS.OE_FIELD_MEANING_ID(+) = 100 -- WEIGHTUNIT
	AND OD_WT_UNITS.ACTION_SEQUENCE(+) = 1
GROUP BY
	DOSES.EVENT_CD,
	DOSES.MEDICATION,
	MED_PRODS.ITEM_ID,
	MED_IDENTIFIER.VALUE,
	ENCOUNTER.LOC_NURSE_UNIT_CD,
	ENCOUNTER.LOC_BED_CD,
	ENCOUNTER.LOC_ROOM_CD,
	ENCNTR_ALIAS.ALIAS,
	PERSON.NAME_FULL_FORMATTED,
	ORDERS.ORIG_ORDER_DT_TM,
	LAST_CHARTED.LAST_CHARTED_DT_TM,
	ORDERS.ORDER_STATUS_CD,
	ORDER_DETAIL.OE_FIELD_DISPLAY_VALUE,
	OD_WT_UNITS.OE_FIELD_DISPLAY_VALUE,
	MED_DISPENSE.STRENGTH,
	MED_DISPENSE.STRENGTH_UNIT_CD,
	MED_DISPENSE.VOLUME,
	MED_DISPENSE.VOLUME_UNIT_CD,
	BAGS_YESTERDAY.BAGS_LAST_24H