WITH PATIENTS AS (
	SELECT DISTINCT
		CLINICAL_EVENT.ENCNTR_ID,
		CLINICAL_EVENT.PERSON_ID,
		ENCOUNTER.DISCH_DT_TM
	FROM
		CE_MED_RESULT,
		CLINICAL_EVENT,
		ENCNTR_LOC_HIST,
		ENCOUNTER
	WHERE
		CLINICAL_EVENT.EVENT_CD IN (
			37557367, -- ketamine
			37556709, -- dexmedetomidine
			37556956, -- FENTanyl
			37557204, -- HYDROmorphone
			37557620, -- morphine Sulfate
			37557455, -- LORAzepam
			37557589, -- midazolam
			37557925 -- propofol
		)
		AND CLINICAL_EVENT.EVENT_END_DT_TM BETWEEN
			pi_to_gmt(TRUNC(SYSDATE) - 14, pi_time_zone(2, @Variable('BOUSER')))
			AND pi_to_gmt(TRUNC(SYSDATE) - 1/86400, pi_time_zone(2, @Variable('BOUSER')))
		-- AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-30'
		AND CLINICAL_EVENT.EVENT_ID = CE_MED_RESULT.EVENT_ID
		AND CE_MED_RESULT.IV_EVENT_CD > 0
		-- AND CE_MED_RESULT.VALID_UNTIL_DT_TM > DATE '2099-12-30'
		AND CLINICAL_EVENT.ENCNTR_ID = ENCNTR_LOC_HIST.ENCNTR_ID
		AND ENCNTR_LOC_HIST.BEG_EFFECTIVE_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
		AND ENCNTR_LOC_HIST.TRANSACTION_DT_TM = (
			SELECT MAX(ELH.TRANSACTION_DT_TM)
			FROM ENCNTR_LOC_HIST ELH
			WHERE
				CLINICAL_EVENT.ENCNTR_ID = ELH.ENCNTR_ID
				AND ELH.TRANSACTION_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
		)
		AND ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD = 3224988589 -- HH S SHIC
		AND ENCNTR_LOC_HIST.END_EFFECTIVE_DT_TM >= CLINICAL_EVENT.EVENT_END_DT_TM
		AND CLINICAL_EVENT.ENCNTR_ID = ENCOUNTER.ENCNTR_ID
)

SELECT DISTINCT
	CLINICAL_EVENT.ENCNTR_ID,
	CLINICAL_EVENT.PERSON_ID,
	CLINICAL_EVENT.EVENT_END_DT_TM,
	pi_from_gmt(CLINICAL_EVENT.EVENT_END_DT_TM, (pi_time_zone(1, @Variable('BOUSER')))) AS DOSE_DATETIME,
	CLINICAL_EVENT.EVENT_ID,
	CLINICAL_EVENT.EVENT_CD,
	LOWER(pi_get_cv_display(CLINICAL_EVENT.EVENT_CD)) AS MEDICATION,
	CLINICAL_EVENT.ORDER_ID,
	CE_MED_RESULT.ADMIN_DOSAGE,
	CE_MED_RESULT.DOSAGE_UNIT_CD,
	pi_get_cv_display(CE_MED_RESULT.DOSAGE_UNIT_CD) AS DOSAGE_UNIT,
	CE_MED_RESULT.INFUSION_RATE,
	CE_MED_RESULT.INFUSION_UNIT_CD,
	pi_get_cv_display(CE_MED_RESULT.INFUSION_UNIT_CD) AS INFUSION_UNIT,
	CE_MED_RESULT.IV_EVENT_CD,
	pi_get_cv_display(CE_MED_RESULT.IV_EVENT_CD) AS IV_EVENT
FROM
	CE_MED_RESULT,
	CLINICAL_EVENT,
	ENCNTR_LOC_HIST,
	PATIENTS
WHERE
	PATIENTS.ENCNTR_ID = CLINICAL_EVENT.ENCNTR_ID
	AND CLINICAL_EVENT.EVENT_CD IN (
		37557367, -- ketamine
		37556709, -- dexmedetomidine
		37556956, -- FENTanyl
		37557204, -- HYDROmorphone
		37557620, -- morphine Sulfate
		37557455, -- LORAzepam
		37557589, -- midazolam
		37557925 -- propofol
	)
	AND PATIENTS.PERSON_ID = CLINICAL_EVENT.PERSON_ID
	AND CLINICAL_EVENT.EVENT_END_DT_TM < PATIENTS.DISCH_DT_TM
	AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-30'
	AND CLINICAL_EVENT.EVENT_ID = CE_MED_RESULT.EVENT_ID
	AND CE_MED_RESULT.IV_EVENT_CD > 0
	AND CE_MED_RESULT.VALID_UNTIL_DT_TM > DATE '2099-12-30'
	AND CLINICAL_EVENT.ENCNTR_ID = ENCNTR_LOC_HIST.ENCNTR_ID
	AND ENCNTR_LOC_HIST.BEG_EFFECTIVE_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
	AND ENCNTR_LOC_HIST.TRANSACTION_DT_TM = (
		SELECT MAX(ELH.TRANSACTION_DT_TM)
		FROM ENCNTR_LOC_HIST ELH
		WHERE
			CLINICAL_EVENT.ENCNTR_ID = ELH.ENCNTR_ID
			AND ELH.TRANSACTION_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
	)
	AND ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD = 3224988589 -- HH S SHIC
	AND ENCNTR_LOC_HIST.END_EFFECTIVE_DT_TM >= CLINICAL_EVENT.EVENT_END_DT_TM
	