WITH DOSES AS (
	SELECT DISTINCT
		CLINICAL_EVENT.ENCNTR_ID,
		CLINICAL_EVENT.PERSON_ID,
		CLINICAL_EVENT.EVENT_END_DT_TM,
		MED_ADMIN_EVENT.SCHEDULED_DT_TM,
		(CLINICAL_EVENT.EVENT_END_DT_TM - MED_ADMIN_EVENT.SCHEDULED_DT_TM) * 24 AS SCHED_ADMIN_HRS,
		CLINICAL_EVENT.EVENT_ID,
		CLINICAL_EVENT.EVENT_CD,
		CE_MED_RESULT.ADMIN_DOSAGE,
		CE_MED_RESULT.DOSAGE_UNIT_CD,
		ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD,
		CASE ORDERS.TEMPLATE_ORDER_ID
			WHEN 0 THEN CLINICAL_EVENT.ORDER_ID
			ELSE ORDERS.TEMPLATE_ORDER_ID
		END AS ORIG_ORDER_ID
	FROM
		CE_MED_RESULT,
		CLINICAL_EVENT,
		ENCNTR_LOC_HIST,
		MED_ADMIN_EVENT,
		ORDERS
	WHERE
		CLINICAL_EVENT.EVENT_CD IN (
			37556091, -- amikacin
			37557069, -- gentamicin
			37558140, -- tacrolimus
			37558218 -- tobramycin
		)
		AND CLINICAL_EVENT.EVENT_END_DT_TM BETWEEN
			DECODE(
				@Prompt('Choose date range', 'A', {'Last Month', 'User-defined'}, mono, free, , , User:0),
				'Last Month', pi_to_gmt(TRUNC(ADD_MONTHS(SYSDATE, -1), 'MONTH'), 'America/Chicago'),
				'User-defined', pi_to_gmt(
					TO_DATE(
						@Prompt('Enter begin date', 'D', , mono, free, persistent, {'12/01/2020 00:00:00'}, User:1),
						pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
					),
					pi_time_zone(1, 'America/Chicago')
				)
			)
			AND DECODE(
				@Prompt('Choose date range', 'A', {'Last Month', 'User-defined'}, mono, free, , , User:0),
				'Last Month', pi_to_gmt(TRUNC(SYSDATE, 'MONTH') - 1/86400, 'America/Chicago'),
				'User-defined', pi_to_gmt(
					TO_DATE(
						@Prompt('Enter end date', 'D', , mono, free, persistent, {'01/01/2021 00:00:00'}, User:2),
						pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
					) - 1/86400,
					pi_time_zone(1, 'America/Chicago')
				)
			)
		AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
		AND CLINICAL_EVENT.EVENT_ID = CE_MED_RESULT.EVENT_ID
		AND CE_MED_RESULT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
		AND CLINICAL_EVENT.ENCNTR_ID = ENCNTR_LOC_HIST.ENCNTR_ID
		AND ENCNTR_LOC_HIST.BEG_EFFECTIVE_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
		AND ENCNTR_LOC_HIST.TRANSACTION_DT_TM = (
			SELECT MAX(ELH.TRANSACTION_DT_TM)
			FROM ENCNTR_LOC_HIST ELH
			WHERE
				CLINICAL_EVENT.ENCNTR_ID = ELH.ENCNTR_ID
				AND ELH.TRANSACTION_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
		)
		AND ENCNTR_LOC_HIST.END_EFFECTIVE_DT_TM >= CLINICAL_EVENT.EVENT_END_DT_TM
		AND ENCNTR_LOC_HIST.LOC_FACILITY_CD IN (
			3310, -- HH HERMANN
			3796, -- HC Childrens
			3821, -- HH Clinics
			3822, -- HH Trans Care
			3823 -- HH Rehab		
		)
		AND CLINICAL_EVENT.ORDER_ID = ORDERS.ORDER_ID
		AND CLINICAL_EVENT.EVENT_ID = MED_ADMIN_EVENT.EVENT_ID
		AND MED_ADMIN_EVENT.EVENT_TYPE_CD <> 227575469 -- Not Given
), ORIG_ORDERS AS (
	SELECT DISTINCT
		DOSES.*,
		ORDERS.ORIG_ORDER_DT_TM,
		PRSNL.NAME_FULL_FORMATTED AS ORDER_PROVIDER,
		PRSNL.POSITION_CD
	FROM
		DOSES,
		ORDER_ACTION,
		ORDERS,
		PRSNL
	WHERE
		DOSES.ORIG_ORDER_ID = ORDERS.ORDER_ID
		AND ORDERS.ORDER_ID = ORDER_ACTION.ORDER_ID
		AND ORDER_ACTION.ACTION_TYPE_CD = 1376 -- Order
		AND ORDER_ACTION.ORDER_PROVIDER_ID = PRSNL.PERSON_ID
)

SELECT
	ENCNTR_ALIAS.ALIAS AS FIN,
	ORIG_ORDERS.ENCNTR_ID,
	pi_get_cv_display(ORIG_ORDERS.EVENT_CD) AS MEDICATION,
	pi_from_gmt(ORIG_ORDERS.ORIG_ORDER_DT_TM, 'America/Chicago') AS ORDER_DATETIME,
	ORIG_ORDERS.ORIG_ORDER_ID,
	pi_from_gmt(ORIG_ORDERS.SCHEDULED_DT_TM, 'America/Chicago') AS SCHED_DATETIME,
	pi_from_gmt(ORIG_ORDERS.EVENT_END_DT_TM, 'America/Chicago') AS ADMIN_DATETIME,
	ORIG_ORDERS.SCHED_ADMIN_HRS,
	ORIG_ORDERS.EVENT_ID,
	ORIG_ORDERS.ADMIN_DOSAGE,
	pi_get_cv_display(ORIG_ORDERS.DOSAGE_UNIT_CD) AS DOSAGE_UNIT,
	pi_get_cv_display(ORIG_ORDERS.LOC_NURSE_UNIT_CD) AS NURSE_UNIT,
	ORIG_ORDERS.ORDER_PROVIDER,
	pi_get_cv_display(ORIG_ORDERS.POSITION_CD) AS PROVIDER_POSITION
FROM
	ENCNTR_ALIAS,
	ORIG_ORDERS
WHERE
	ORIG_ORDERS.ENCNTR_ID = ENCNTR_ALIAS.ENCNTR_ID
	AND ENCNTR_ALIAS.ENCNTR_ALIAS_TYPE_CD = 619 -- FIN NBR
	AND ENCNTR_ALIAS.ACTIVE_IND = 1
