SELECT
	ORDERS.ENCNTR_ID,
	ORDERS.ORDER_ID,
	pi_get_cv_display(ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD) AS NURSE_UNIT,
	pi_from_gmt(ORDERS.ORIG_ORDER_DT_TM, (pi_time_zone(1, @Variable('BOUSER')))) AS ORDER_DATETIME,
	pi_from_gmt(ORDER_REVIEW.REVIEW_DT_TM, (pi_time_zone(1, @Variable('BOUSER')))) AS REVIEW_DATETIME,
	(ORDER_REVIEW.REVIEW_DT_TM - ORDERS.ORIG_ORDER_DT_TM) * 24 * 60 AS ORDER_VERIFY_MIN,
	CASE ORDER_REVIEW.REVIEWED_STATUS_FLAG
		WHEN 1 THEN 'Accepted'
		WHEN 2 THEN 'Rejected'
		WHEN 5 THEN 'Reviewed'
	END AS VERIFIED_STATUS,
	pi_get_cv_display(FREQUENCY_SCHEDULE.FREQUENCY_CD) AS FREQ,
	ORDER_DETAIL.OE_FIELD_DISPLAY_VALUE AS PRIORITY
FROM 
	ENCNTR_LOC_HIST,
	FREQUENCY_SCHEDULE,
	ORDER_DETAIL,
	ORDER_REVIEW,
	ORDERS
WHERE
	ORDERS.CATALOG_CD = 9929631 -- tranexamic acid
	AND ORDERS.CATALOG_TYPE_CD = 1363
	AND	ORDERS.TEMPLATE_ORDER_FLAG IN (0, 1)
	AND ORDERS.ORIG_ORD_AS_FLAG = 0
	AND ORDERS.ORIG_ORDER_DT_TM BETWEEN
		pi_to_gmt(DATE '2019-09-01', pi_time_zone(2, @Variable('BOUSER')))
		AND pi_to_gmt(TRUNC(SYSDATE) - (1 / 86400), pi_time_zone(2, @Variable('BOUSER')))
	AND ORDERS.ENCNTR_ID = ENCNTR_LOC_HIST.ENCNTR_ID
	AND ENCNTR_LOC_HIST.BEG_EFFECTIVE_DT_TM <= ORDERS.ORIG_ORDER_DT_TM
	AND ENCNTR_LOC_HIST.TRANSACTION_DT_TM = (
		SELECT MAX(ELH.TRANSACTION_DT_TM)
		FROM ENCNTR_LOC_HIST ELH
		WHERE
			ORDERS.ENCNTR_ID = ELH.ENCNTR_ID
			AND ELH.TRANSACTION_DT_TM <= ORDERS.ORIG_ORDER_DT_TM
	)
	AND ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD IN (
		1101289, -- HH WC5
		77842455, -- HH WC6N
		923835653, -- HH WCAN
		1150050540 -- HH WCOR
	)			
	AND ENCNTR_LOC_HIST.END_EFFECTIVE_DT_TM >= ORDERS.ORIG_ORDER_DT_TM
	AND ORDERS.FREQUENCY_ID = FREQUENCY_SCHEDULE.FREQUENCY_ID
	AND ORDERS.ORDER_ID = ORDER_REVIEW.ORDER_ID
	AND ORDER_REVIEW.ACTION_SEQUENCE = 1
	AND ORDER_REVIEW.REVIEW_TYPE_FLAG = 3
	AND ORDER_REVIEW.REVIEWED_STATUS_FLAG = 1
	AND ORDERS.ORDER_ID = ORDER_DETAIL.ORDER_ID(+)
	AND ORDER_DETAIL.ACTION_SEQUENCE(+) = 1
	AND ORDER_DETAIL.OE_FIELD_MEANING_ID(+) IN (
		127, -- PRIORITY
		141 -- RXPRIORITY
	)
