SELECT DISTINCT
	CLINICAL_EVENT.ENCNTR_ID,
	CLINICAL_EVENT.EVENT_ID,
	CLINICAL_EVENT.ORDER_ID,
	ORDERS.TEMPLATE_ORDER_ID,
	pi_from_gmt(ORDERS.ORIG_ORDER_DT_TM, (pi_time_zone(1, @Variable('BOUSER')))) AS ORDER_DATETIME,
	pi_from_gmt(CLINICAL_EVENT.EVENT_END_DT_TM, (pi_time_zone(1, @Variable('BOUSER')))) AS DOSE_DATETIME,
	pi_get_cv_display(ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD) AS NURSE_UNIT,
	CE_MED_RESULT.ADMIN_DOSAGE AS DOSE,
	CE_MED_RESULT.INFUSION_RATE AS RATE,
	pi_get_cv_display(CE_MED_RESULT.IV_EVENT_CD) AS IV_EVENT
FROM 
	CE_MED_RESULT,
	CLINICAL_EVENT,
	ENCNTR_LOC_HIST,
	ORDERS
WHERE
	CLINICAL_EVENT.EVENT_CD = 48069081 -- tranexamic acid
	AND CLINICAL_EVENT.EVENT_END_DT_TM BETWEEN
		pi_to_gmt(DATE '2019-09-01', pi_time_zone(2, @Variable('BOUSER')))
		AND pi_to_gmt(TRUNC(SYSDATE) - (1 / 86400), pi_time_zone(2, @Variable('BOUSER')))
	AND CLINICAL_EVENT.EVENT_ID = CE_MED_RESULT.EVENT_ID
	AND (
		CE_MED_RESULT.ADMIN_DOSAGE > 0 
		OR CE_MED_RESULT.IV_EVENT_CD = 688706 -- Begin Bag
	)
	AND CLINICAL_EVENT.ENCNTR_ID = ENCNTR_LOC_HIST.ENCNTR_ID
	AND ENCNTR_LOC_HIST.BEG_EFFECTIVE_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
	AND ENCNTR_LOC_HIST.TRANSACTION_DT_TM = (
		SELECT MAX(ELH.TRANSACTION_DT_TM)
		FROM ENCNTR_LOC_HIST ELH
		WHERE
			CLINICAL_EVENT.ENCNTR_ID = ELH.ENCNTR_ID
			AND ELH.TRANSACTION_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
	)
	AND ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD IN (
		1101289, -- HH WC5
		77842455, -- HH WC6N
		923835653, -- HH WCAN
		1150050540 -- HH WCOR
	)			
	AND ENCNTR_LOC_HIST.END_EFFECTIVE_DT_TM >= CLINICAL_EVENT.EVENT_END_DT_TM 
	AND CLINICAL_EVENT.ORDER_ID = ORDERS.ORDER_ID
