WITH DOSES AS (
	SELECT DISTINCT
		CLINICAL_EVENT.ENCNTR_ID,
		CASE
			WHEN ORDERS.TEMPLATE_ORDER_ID = 0 THEN ORDERS.ORDER_ID
			ELSE ORDERS.TEMPLATE_ORDER_ID
		END AS ORIG_ORDER_ID
		-- pi_from_gmt(CLINICAL_EVENT.EVENT_END_DT_TM, 'America/Chicago') AS EVENT_DATETIME,
		-- TRUNC(pi_from_gmt(CLINICAL_EVENT.EVENT_END_DT_TM, 'America/Chicago')) AS EVENT_DAY,	
		-- TRUNC(pi_from_gmt(CLINICAL_EVENT.EVENT_END_DT_TM, 'America/Chicago'), 'MONTH') AS EVENT_MONTH,
		-- CLINICAL_EVENT.EVENT_ID,
		-- pi_get_cv_display(ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD) AS NURSE_UNIT
	FROM 
		CE_MED_RESULT,
		CLINICAL_EVENT,
		ENCNTR_LOC_HIST,
		ORDERS
	WHERE
		CLINICAL_EVENT.EVENT_CD = 37558315 -- vancomycin
		AND CLINICAL_EVENT.EVENT_END_DT_TM BETWEEN
            pi_to_gmt(
                TO_DATE(
                    @Prompt('Enter begin date', 'D', , mono, free, persistent, {'07/01/2021 00:00:00'}, User:0), 
                    pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
                ), 
                pi_time_zone(1, 'America/Chicago')
            )
            AND pi_to_gmt(
                TO_DATE(
                    @Prompt('Enter end date', 'D', , mono, free, persistent, {'07/01/2022 00:00:00'}, User:1), 
                    pi_get_dm_info_char_gen('Date Format Mask|FT','PI EXP|Systems Configuration|Date Format Mask')
                ) - 1/86400, 
                pi_time_zone(1, 'America/Chicago')
            )	
		AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
		AND CLINICAL_EVENT.EVENT_ID = CE_MED_RESULT.EVENT_ID
		-- AND CE_MED_RESULT.IV_EVENT_CD > 0
		AND CE_MED_RESULT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
		AND CLINICAL_EVENT.ENCNTR_ID = ENCNTR_LOC_HIST.ENCNTR_ID
		AND ENCNTR_LOC_HIST.BEG_EFFECTIVE_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
		AND ENCNTR_LOC_HIST.TRANSACTION_DT_TM = (
			SELECT MAX(ELH.TRANSACTION_DT_TM)
			FROM ENCNTR_LOC_HIST ELH
			WHERE
				CLINICAL_EVENT.ENCNTR_ID = ELH.ENCNTR_ID
				AND ELH.TRANSACTION_DT_TM <= CLINICAL_EVENT.EVENT_END_DT_TM
				AND ELH.ACTIVE_IND = 1
		)
		AND ENCNTR_LOC_HIST.END_EFFECTIVE_DT_TM >= CLINICAL_EVENT.EVENT_END_DT_TM
		AND ENCNTR_LOC_HIST.ACTIVE_IND = 1   
		AND ENCNTR_LOC_HIST.LOC_FACILITY_CD IN (
			3310, -- HH HERMANN
			-- 3796, -- HC Childrens
			-- 3821, -- HH Clinics
			3822, -- HH Trans Care
			3823 -- HH Rehab		
		)
		AND CLINICAL_EVENT.ORDER_ID = ORDERS.ORDER_ID
)

SELECT DISTINCT
	DOSES.ENCNTR_ID,
	DOSES.ORIG_ORDER_ID,
	MED_IDENTIFIER.VALUE AS PRODUCT,
	pi_from_gmt(DISPENSE_HX.DISPENSE_DT_TM, 'America/Chicago') AS DISPENSE_DATETIME,
	TRUNC(pi_from_gmt(DISPENSE_HX.DISPENSE_DT_TM, 'America/Chicago')) AS DISPENSE_DAY,
	TRUNC(pi_from_gmt(DISPENSE_HX.DISPENSE_DT_TM, 'America/Chicago'), 'MONTH') AS DISPENSE_MONTH,
	pi_get_cv_display(DISPENSE_HX.DISP_EVENT_TYPE_CD) AS DISP_EVENT_TYPE,
	pi_get_cv_display(DISPENSE_HX.DISP_SR_CD) AS DISP_FROM,
	-- DISPENSE_HX.DOSES,
	-- DISPENSE_HX.CHARGE_IND,
	CASE
		WHEN pi_get_cv_display(DISP_EVENT_TYPE_CD) IN ('Device Return', 'Manual Credit') THEN DISPENSE_HX.DOSES * DISPENSE_HX.CHARGE_IND * -1
		ELSE DISPENSE_HX.DOSES * DISPENSE_HX.CHARGE_IND
	END AS DISP_AMT,
	-- ORDER_PRODUCT.ITEM_ID,
	-- ORDER_PRODUCT.DOSE_QUANTITY,
	-- pi_get_cv_display(ORDER_PRODUCT.DOSE_QUANTITY_UNIT_CD) AS DOSE_QUANTITY_UNIT,
	pi_get_cv_display(ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD) AS NURSE_UNIT
FROM
	DISPENSE_HX,
	DOSES,
	ENCNTR_LOC_HIST,
	MED_IDENTIFIER,
	ORDER_PRODUCT
WHERE
	DOSES.ORIG_ORDER_ID = DISPENSE_HX.ORDER_ID
	AND DOSES.ORIG_ORDER_ID = ORDER_PRODUCT.ORDER_ID
	-- AND ORDER_PRODUCT.ACTION_SEQUENCE = 1
	AND ORDER_PRODUCT.INGRED_SEQUENCE = 1
	AND ORDER_PRODUCT.ITEM_ID = MED_IDENTIFIER.ITEM_ID
	AND MED_IDENTIFIER.MED_IDENTIFIER_TYPE_CD = 1564 -- Generic Name
	AND MED_IDENTIFIER.MED_PRODUCT_ID = 0
	AND MED_IDENTIFIER.ITEM_ID IN (
		92003850, -- vancomycin 1.25 gm / NS 250 ml (Premix)
		85289538, -- vancomycin 1.5 gm / NS 250 ml (Premix)
		92044160, -- Vancomycin 2 gm / NS 500 ml (premixed)
		193581589 -- vancomycin 750 mg in NS 250 mL
	)
	AND DOSES.ENCNTR_ID = ENCNTR_LOC_HIST.ENCNTR_ID
	AND ENCNTR_LOC_HIST.BEG_EFFECTIVE_DT_TM <= DISPENSE_HX.DISPENSE_DT_TM
	AND ENCNTR_LOC_HIST.TRANSACTION_DT_TM = (
		SELECT MAX(ELH.TRANSACTION_DT_TM)
		FROM ENCNTR_LOC_HIST ELH
		WHERE
			DOSES.ENCNTR_ID = ELH.ENCNTR_ID
			AND ELH.TRANSACTION_DT_TM <= DISPENSE_HX.DISPENSE_DT_TM
			AND ELH.ACTIVE_IND = 1
	)
	AND ENCNTR_LOC_HIST.END_EFFECTIVE_DT_TM >= DISPENSE_HX.DISPENSE_DT_TM
	AND ENCNTR_LOC_HIST.ACTIVE_IND = 1   


