---
title: "Cathflo (Alteplase) Utilization"
author: "Brian Gulbis, PharmD, BCPS"
date: 'Updated on: `r format(Sys.Date(), "%B %d, %Y")`'
output: 
    html_document:
        code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r}
library(tidyverse)
library(lubridate)
library(edwr)
library(plotly)

dir_raw <- "../data/raw/2018-05_cathflo"

# run MBO query
#   * Patients - by Medication (Generic)
#       - Facility (Curr): HH HERMANN;HH Trans Care;HH Rehab;HH Clinics
#       - Medication (Generic): alteplase
#       - Admit date: 2/1/2018 - 4/30/2018

# pts <- read_data(dir_raw, "patients", FALSE) %>%
#     as.patients()
# 
# mbo_pts <- concat_encounters(pts$millennium.id)

# run MBO query
#   * Medications - Inpatient - Prompt
#       - Medication (Generic): alteplase


# run MBO query
#   * Patients - by Order - no Building

pts_orders <- read_data(dir_raw, "patients-orders", FALSE) %>%
    as.patients()

mbo_orders <- concat_encounters(pts_orders$millennium.id)

# run MBO query
#   * Medications - Inpatient - Prompt
#       - Medication (Generic): alteplase
#   * Orders Meds - Details with Volume


cathflo <- "alteplase 1 mg INJ (2 mg/2 ml)"

orders <- read_data(dir_raw, "orders-details", FALSE) %>%
    as.order_detail(
        extras = c(
            "order.product" = "Mnemonic (Product)",
            "order.as" = "Mnemonic (Ordered As Name)"
        )
    ) %>%
    mutate_at("ingredient.dose", as.numeric) %>%
    filter(ingredient.dose <= 4)
    # filter(order.product == cathflo | order.as == cathflo)

meds <- read_data(dir_raw, "meds-inpt", FALSE) %>%
    as.meds_inpt() %>%
    filter(
        is.na(event.tag),
        med.dose <= 2
    )

```

```{r, fig.cap="Number of orders for alteplase doses given over a 3 month period"}
orders %>%
    count(ingredient.dose) %>%
    mutate_at("ingredient.dose", factor) %>%
    plot_ly() %>%
    add_bars(x = ~ingredient.dose, y = ~n) %>%
    layout(
        xaxis = list(title = "Dose (mg)"),
        yaxis = list(title = "Number of orders")
    )
```

```{r, fig.cap="Number of medication administrations for alteplase doses given over a 3 month period"}
meds %>%
    count(med.dose) %>%
    mutate_at("med.dose", factor) %>%
    plot_ly() %>%
    add_bars(x = ~med.dose, y = ~n) %>%
    layout(
        xaxis = list(title = "Dose (mg)"),
        yaxis = list(title = "Number of doses")
    )
```
