---
title: "Pharmacy Order Volume"
subtitle: "April 1 - 14, 2018"
author: "Brian Gulbis, PharmD, BCPS"
date: 'Updated on: `r format(Sys.Date(), "%B %d, %Y")`'
output: 
    html_document:
        code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r}
library(tidyverse)
library(plotly)
library(RColorBrewer)
library(themebg)

x <- dirr::get_rds("../data/tidy/2018-05_order-volume")

rm(x)

pavilions <- c(
    "HH Hermann",
    "HH Cullen",
    "HH Jones",
    "HH HVI",
    "HC Childrens"
)

```

```{r, fig.cap="Number of original orders placed by hour of the day"}
data_orders %>%
    filter(
        !is.na(facility),
        facility != "other",
        building %in% pavilions
    ) %>%
    count(facility, building, order.hour) %>%
    plot_ly(colors = brewer.pal(length(pavilions), "Paired")) %>%
    add_bars(
        x = ~order.hour, 
        y = ~n,
        color = ~building) %>%
    layout(
        barmode = "stack",
        xaxis = list(
            title = "Hour of day",
            tick0 = 0,
            dtick = 6
        ),
        yaxis = list(
            title = "Number of orders"
        )
    )

```

```{r, fig.cap="Number of order actions by hour of the day"}
data_actions %>%
    filter(
        !is.na(facility),
        facility != "other",
        building %in% pavilions
    ) %>%
    count(facility, building, action.hour) %>%
    plot_ly(colors = brewer.pal(length(pavilions), "Paired")) %>%
    add_bars(
        x = ~action.hour, 
        y = ~n,
        color = ~building) %>%
    layout(
        barmode = "stack",
        xaxis = list(
            title = "Hour of day",
            tick0 = 0,
            dtick = 6
        ),
        yaxis = list(
            title = "Number of order actions"
        )
    )
```

```{r, fig.cap="Number of order actions by hour of the day, split by type of action", eval=FALSE}
df <- data_actions %>%
    filter(
        !is.na(facility),
        facility != "other",
        building %in% pavilions
    ) %>%
    count(action.type, sort = TRUE)

df_all <- data_actions %>%
    filter(
        !is.na(facility),
        facility != "other",
        building %in% pavilions
    ) %>%
    count(action.type, action.hour) %>%
    mutate_at("action.type", factor, levels = df$action.type)

df_facility <- data_actions %>%
    filter(
        !is.na(facility),
        facility != "other",
        building %in% pavilions
    ) %>%
    count(facility, action.type, action.hour) %>%
    mutate_at("action.type", factor, levels = df$action.type)

df_adult <- df_facility %>%
    filter(facility == "Adult")

df_pedi <- df_facility %>%
    filter(facility == "Children\'s")


    # spread(facility, n, fill = 0L) %>%
    # rename(
    #     adult = Adult,
    #     pedi = `Children's`
    # ) %>%
    # mutate(all = adult + pedi) %>%

df_all %>%
    plot_ly(
        x = ~action.hour,
        y = ~n,
        color = ~action.type,
        colors = brewer.pal(
            nrow(df), 
            "Paired"
        ),
        legendgroup = ~action.type
    ) %>%
    add_bars(
        # y = ~all,
        # name = "all",
        visible = TRUE
    ) %>%
    add_bars(
        data = df_adult,
        # y = ~adult, 
        # name = "adult",
        visible = FALSE
    ) %>%
    add_bars(
        data = df_pedi,
        # y = ~pedi,
        # name = "pedi",
        visible = FALSE
    ) %>%
    layout(
        barmode = "stack",
        title = "All Areas",
        xaxis = list(
            title = "Hour of day",
            tick0 = 0,
            dtick = 6
        ),
        yaxis = list(
            title = "Number of order actions"
        ),
        updatemenus = list(
            list(
                y = 0.9,
                buttons = list(
                    list(
                        method = "update",
                        args = list(
                            list(visible = c(TRUE, FALSE, FALSE)),
                            list(title = "All Areas")
                        ),
                        label = "All"
                    ),
                    list(
                        method = "update",
                        args = list(
                            list(visible = c(FALSE, TRUE, FALSE)),
                            list(title = "Adult Only")
                        ),
                        label = "Adult"
                    ),
                    list(
                        method = "update",
                        args = list(
                            list(visible = c(FALSE, FALSE, TRUE)),
                            list(title = "Children\'s Only")
                        ),
                        label = "Childrens"
                    )
                )
            )
        )
    )
```

```{r, fig.cap="Number of order actions by hour of the day, split by type of action"}
df <- data_actions %>%
    filter(
        !is.na(facility),
        facility != "other",
        building %in% pavilions
    ) %>%
    count(action.type, sort = TRUE)

# df_all <- data_actions %>%
#     filter(
#         !is.na(facility),
#         facility != "other",
#         building %in% pavilions
#     ) %>%
#     count(action.type, action.hour) %>%
#     mutate_at("action.type", factor, levels = df$action.type)

sub_actions <- function(x) {
    x %>%
        plot_ly(        
            colors = brewer.pal(
                nrow(df), 
                "Paired"
            )
        ) %>%
        add_bars(
            x = ~action.hour,
            y = ~n,
            color = ~action.type,
            legendgroup = ~action.type,
            showlegend = x$facility[1] == "Adult"
        ) %>%
        layout(
            barmode = "stack",
            xaxis = list(
                title = x$facility[1],
                tick0 = 0,
                dtick = 6
            )
        )
    
}

df_facility <- data_actions %>%
    filter(
        !is.na(facility),
        facility != "other",
        building %in% pavilions
    ) %>%
    count(facility, action.type, action.hour) %>%
    mutate_at("action.type", factor, levels = df$action.type)

df_facility %>%
    group_by(facility) %>%
    do(p = sub_actions(.)) %>%
    subplot(nrows = 1, shareX = TRUE, shareY = TRUE) %>%
    layout(
        # xaxis = list(title = "Hour of day"),
        yaxis = list(title = "Number of order actions")
    )

```

```{r, fig.cap="Number of order actions handled by a pharmacist / tech by hour of the day, split by pavilion"}
data_actions %>%
    filter(
        !is.na(facility),
        facility != "other",
        building %in% pavilions,
        (
            str_detect(
                action.provider.role,
                regex("pharm", ignore_case = TRUE)
            ) |
                str_detect(
                    action.provider,
                    regex("rph", ignore_case = TRUE)
                )
        )
    ) %>%
    count(facility, building, action.hour, sort = TRUE) %>%
    plot_ly(colors = brewer.pal(length(pavilions), "Paired")) %>%
    add_bars(
        x = ~action.hour,
        y = ~n, 
        color = ~building 
    ) %>%
    layout(
        barmode = "stack",
        xaxis = list(
            title = "Hour of day",
            tick0 = 0,
            dtick = 6
        ),
        yaxis = list(
            title = "Number of order actions"
        )
    )
```

```{r, fig.cap="Number of order actions handled by a pharmacist / tech by hour of the day, split by action type"}
data_actions %>%
    filter(
        !is.na(facility),
        facility != "other",
        building %in% pavilions,
        (
            str_detect(
                action.provider.role,
                regex("pharm", ignore_case = TRUE)
            ) |
                str_detect(
                    action.provider,
                    regex("rph", ignore_case = TRUE)
                )
        )
    ) %>%
    count(facility, action.type, action.hour, sort = TRUE) %>%
    mutate_at("action.type", as_factor) %>%
    plot_ly(
        colors = brewer.pal(
            nrow(distinct(data_actions, action.type)), 
            "Paired"
        )
    ) %>%
    add_bars(
        x = ~action.hour,
        y = ~n, 
        color = ~action.type 
    ) %>%
    layout(
        barmode = "stack",
        xaxis = list(
            title = "Hour of day",
            tick0 = 0,
            dtick = 6
        ),
        yaxis = list(
            title = "Number of order actions"
        )
    )
```

```{r, fig.cap="Number of original orders placed by day of the week"}
data_orders %>%
    filter(
        !is.na(facility),
        facility != "other",
        building %in% pavilions
    ) %>%
    count(facility, building, order.day) %>%
    plot_ly(colors = brewer.pal(length(pavilions), "Paired")) %>%
    add_bars(
        x = ~order.day, 
        y = ~n,
        color = ~building) %>%
    layout(
        barmode = "stack",
        xaxis = list(
            title = "Day of week"
        ),
        yaxis = list(
            title = "Number of orders"
        )
    )

```

```{r, fig.cap="Number of order actions by day of week"}
data_actions %>%
    filter(
        !is.na(facility),
        facility != "other",
        building %in% pavilions
    ) %>%
    count(facility, building, action.day) %>%
    plot_ly(colors = brewer.pal(length(pavilions), "Paired")) %>%
    add_bars(
        x = ~action.day, 
        y = ~n,
        color = ~building) %>%
    layout(
        barmode = "stack",
        xaxis = list(
            title = "Day of week"
        ),
        yaxis = list(
            title = "Number of order actions"
        )
    )
```

```{r, fig.cap="Number of orders by hour of the day per pavilion by type of location"}

small_mult_hour <- function(x) {
    x %>%
        plot_ly(
            colors = brewer.pal(
                length(levels(x$location.group)),
                "Paired"
            )
        ) %>%
        add_bars(
            x = ~order.hour, 
            y = ~n,
            color = ~location.group,
            legendgroup = ~location.group,
            showlegend = x$building[1] == "HC Childrens"
        ) %>%
        layout(
            barmode = "stack",
            xaxis = list(
                tick0 = 0,
                dtick = 6
            ),
            yaxis = list(title = x$building[1])
        )
}

df <- data_orders %>%
    filter(
        !is.na(facility),
        facility != "other",
        building %in% pavilions
    ) %>%
    count(building, location.group, order.hour) %>%
    mutate_at("location.group", factor) %>%
    spread(location.group, n, fill = 0L, drop = FALSE) %>%
    gather(location.group, n, -building, -order.hour) %>%
    mutate_at("location.group", factor) 

df %>%
    group_by(building) %>%
    do(p = small_mult_hour(.)) %>%
    subplot(nrows = length(pavilions), shareX = TRUE, shareY = TRUE) %>%
    layout(
        xaxis = list(title = "Hour of day")
        # yaxis = list(title = "Number of orders")
    )

```


```{r, fig.cap="Number of orders by day of week per pavilion by type of location"}

small_mult_day <- function(x) {
    x %>%
        plot_ly(
            colors = brewer.pal(
                length(levels(x$location.group)),
                "Paired"
            )
        ) %>%
        add_bars(
            x = ~order.day, 
            y = ~n,
            color = ~location.group,
            legendgroup = ~location.group,
            showlegend = x$building[1] == "HC Childrens"
        ) %>%
        layout(
            barmode = "stack",
            yaxis = list(title = x$building[1])
        )
}

df <- data_orders %>%
    filter(
        !is.na(facility),
        facility != "other",
        building %in% pavilions
    ) %>%
    count(building, location.group, order.day) %>%
    mutate_at("location.group", factor) %>%
    spread(location.group, n, fill = 0L, drop = FALSE) %>%
    gather(location.group, n, -building, -order.day) %>%
    mutate_at("location.group", factor) 

df %>%
    group_by(building) %>%
    do(p = small_mult_day(.)) %>%
    subplot(nrows = length(pavilions), shareX = TRUE, shareY = TRUE) %>%
    layout(
        xaxis = list(title = "Day of week")
        # yaxis = list(title = "Number of orders")
    )

```


